import ply.lex as lex

S = 0
S3 = 1
S4 = 2
O = 3
F = 4
F2 = 5
F3 = 6
L = 7
C = 8
I = 9
E = 10
W = 11
G = 12
P = 13
Q = 14
Q3 = 15
Q4 = 16
D = 17
D2 = 18
V = 19
V1 = 20
V3 = 21
V5 = 22
V6 = 23
V2 = 24
V4 = 25
B = 26
B1 = 27
K = 28
Q1 = 29
A = 30
T1 = 31
Z = 32
S1 = 33
T2 = 34
T3 = 35
T4 = 36
T5 = 37
ST = 38
ST2 = 39

# List of token names. Required
tokens = [
    "LPAREN",
    "RPAREN",
    "inicioBloque",
    "finBloque",
    "LBRACKET",
    "RBRACKET",
    "CONST_INT",
    "CONST_FLOAT",
    "CONST_CHAR",
    "INCREMENT",  # ++
    "DECREMENT",  # --
    "PLUS",
    "MINUS",
    "TIMES",
    "DIVIDE",
    "MOD",
    "AND",
    "OR",
    "DIFFERENT",
    "EQUALS",
    "LESS",
    "GREATER",
    "ID",
    "COMMA",
    "finInstruccion",  # ;
    "COMMENT",
    "COMMENTBLOCK",
    "ASSIGNMENT",  # =
    "DOT",  # .
    "eof"  # $
]

reserved_words = {
    "main": "main",
    "int": "int",
    "void": "void",
    "return": "return",
    "float": "float",
    "char": "char",
    "struct": "struct",
    "if": "if",
    "else": "else",
    "do": "do",
    "while": "while",
    "for": "for",
    'break': 'break',  # se debe poner gramatica
}

# Add words reserved to tokens array
tokens += list(reserved_words.values())

# Regular expression rules for simple tokens
t_PLUS = r'\+'
t_MINUS = r'-'
t_TIMES = r'\*'
t_DIVIDE = r'/'
t_MOD = r"\%"
t_AND = r"\&\&"
t_OR = r"\|\|"
t_INCREMENT = r"\+\+"
t_DECREMENT = r"\-\-"
t_DIFFERENT = r"\!\="
t_EQUALS = r"\=\="
t_LESS = r"\<"
t_GREATER = r"\>"
t_LPAREN = r"\("
t_RPAREN = r"\)"
t_LBRACKET = r"\["
t_RBRACKET = r"\]"
t_inicioBloque = r'\{'
t_finBloque = r'\}'
t_finInstruccion = r'\;'
t_ASSIGNMENT = r"\="
t_COMMA = r'\,'
t_DOT = r'\.'
t_eof = r'\$'


# A regular expression rule

def t_CONST_CHAR(t):
    r"(\')(.*)(\')"
    return t


def t_COMMENT(t):
    r"\/\/.*"
    pass


def t_COMMENTBLOCK(t):
    r"\/\*(.|\n)*\*\/"
    pass


def t_ID(t):
    r'([a-z]|[A-Z]|_)([a-z]|[A-Z]|\d|_)*'
    t.type = reserved_words.get(t.value, "ID")  # Check for reserved words
    return t


def t_CONST_FLOAT(t):
    r'[-+]?[0-9]+(\.([0-9]+)?([eE][-+]?[0-9]+)?|[eE][-+]?[0-9]+)'
    t.value = float(t.value)
    return t


def t_CONST_INT(t):
    r"\d+(\.\d+)?"
    t.value = int(t.value)
    return t


# Define a rule so we can track line numbers
def t_newline(t):
    r'\n+'
    t.lexer.lineno += len(t.value)


# A string containing ignored characters (spaces and tabs)
t_ignore = " \t"


# Error handling rule
def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    t.lexer.skip(1)
    return t


tabla = [
    [S, 'ID', None],
    [S, 'main', None],
    [S, 'LPAREN', None],
    [S, 'RPAREN', None],
    [S, 'inicioBloque', None],
    [S, 'finBloque', None],
    [S, 'LESS', None],
    [S, 'GREATER', None],
    [S, 'EQUALS', None],
    [S, 'DIFFERENT', None],
    [S, 'AND', None],
    [S, 'OR', None],
    [S, 'CONST_INT', None],
    [S, 'CONST_FLOAT', None],
    [S, 'CONST_CHAR', None],
    [S, 'if', None],
    [S, 'else', None],
    [S, 'while', None],
    [S, 'do', None],
    [S, 'finInstruccion', None],
    [S, 'INCREMENT', None],
    [S, 'DECREMENT', None],
    [S, 'for', None],
    [S, 'int', [D2, S3]],
    [S, 'ASSIGNMENT', None],
    [S, 'float', [D2, S3]],
    [S, 'char', [D2, S3]],
    [S, 'void', [D2, S3]],
    [S, 'COMMA', None],
    [S, 'LBRACKET', None],
    [S, 'RBRACKET', None],
    [S, 'DOT', None],
    [S, 'PLUS', None],
    [S, 'MINUS', None],
    [S, 'TIMES', None],
    [S, 'DIVIDE', None],
    [S, 'MOD', None],
    [S, 'struct', [ST, S]],
    [S, 'return', None],
    [S, 'eof', None],

    [S3, 'ID', ['ID', S4, S]],
    [S3, 'main', ['main', S4]],
    [S3, 'LPAREN', None],
    [S3, 'RPAREN', None],
    [S3, 'inicioBloque', None],
    [S3, 'finBloque', None],
    [S3, 'LESS', None],
    [S3, 'GREATER', None],
    [S3, 'EQUALS', None],
    [S3, 'DIFFERENT', None],
    [S3, 'AND', None],
    [S3, 'OR', None],
    [S3, 'CONST_INT', None],
    [S3, 'CONST_FLOAT', None],
    [S3, 'CONST_CHAR', None],
    [S3, 'if', None],
    [S3, 'else', None],
    [S3, 'while', None],
    [S3, 'do', None],
    [S3, 'finInstruccion', None],
    [S3, 'INCREMENT', None],
    [S3, 'DECREMENT', None],
    [S3, 'for', None],
    [S3, 'int', None],
    [S3, 'ASSIGNMENT', None],
    [S3, 'float', None],
    [S3, 'char', None],
    [S3, 'void', None],
    [S3, 'COMMA', None],
    [S3, 'LBRACKET', None],
    [S3, 'RBRACKET', None],
    [S3, 'DOT', None],
    [S3, 'PLUS', None],
    [S3, 'MINUS', None],
    [S3, 'TIMES', None],
    [S3, 'DIVIDE', None],
    [S3, 'MOD', None],
    [S3, 'struct', None],
    [S3, 'return', None],
    [S3, 'eof', None],

    [S4, 'ID', None],
    [S4, 'main', None],
    [S4, 'LPAREN', ['LPAREN', T4, 'RPAREN', 'inicioBloque', S1, 'finBloque']],
    [S4, 'RPAREN', None],
    [S4, 'inicioBloque', None],
    [S4, 'finBloque', None],
    [S4, 'LESS', None],
    [S4, 'GREATER', None],
    [S4, 'EQUALS', None],
    [S4, 'DIFFERENT', None],
    [S4, 'AND', None],
    [S4, 'OR', None],
    [S4, 'CONST_INT', None],
    [S4, 'CONST_FLOAT', None],
    [S4, 'CONST_CHAR', None],
    [S4, 'if', None],
    [S4, 'else', None],
    [S4, 'while', None],
    [S4, 'do', None],
    [S4, 'finInstruccion', None],
    [S4, 'INCREMENT', None],
    [S4, 'DECREMENT', None],
    [S4, 'for', None],
    [S4, 'int', None],
    [S4, 'ASSIGNMENT', None],
    [S4, 'float', None],
    [S4, 'char', None],
    [S4, 'void', None],
    [S4, 'COMMA', None],
    [S4, 'LBRACKET', None],
    [S4, 'RBRACKET', None],
    [S4, 'DOT', None],
    [S4, 'PLUS', None],
    [S4, 'MINUS', None],
    [S4, 'TIMES', None],
    [S4, 'DIVIDE', None],
    [S4, 'MOD', None],
    [S4, 'struct', None],
    [S4, 'return', None],
    [S4, 'eof', None],

    [O, 'ID', None],
    [O, 'main', None],
    [O, 'LPAREN', None],
    [O, 'RPAREN', None],
    [O, 'inicioBloque', None],
    [O, 'finBloque', None],
    [O, 'LESS', ['LESS']],
    [O, 'GREATER', ['GREATER']],
    [O, 'EQUALS', ['EQUALS']],
    [O, 'DIFFERENT', ['DIFFERENT']],
    [O, 'AND', ['AND']],
    [O, 'OR', ['OR']],
    [O, 'CONST_INT', None],
    [O, 'CONST_FLOAT', None],
    [O, 'CONST_CHAR', None],
    [O, 'if', None],
    [O, 'else', None],
    [O, 'while', None],
    [O, 'do', None],
    [O, 'finInstruccion', None],
    [O, 'INCREMENT', None],
    [O, 'DECREMENT', None],
    [O, 'for', None],
    [O, 'int', None],
    [O, 'ASSIGNMENT', None],
    [O, 'float', None],
    [O, 'char', None],
    [O, 'void', None],
    [O, 'COMMA', None],
    [O, 'LBRACKET', None],
    [O, 'RBRACKET', None],
    [O, 'DOT', None],
    [O, 'PLUS', None],
    [O, 'MINUS', None],
    [O, 'TIMES', None],
    [O, 'DIVIDE', None],
    [O, 'MOD', None],
    [O, 'struct', None],
    [O, 'return', None],
    [O, 'eof', None],

    [F, 'ID', ['ID']],
    [F, 'main', None],
    [F, 'LPAREN', None],
    [F, 'RPAREN', None],
    [F, 'inicioBloque', None],
    [F, 'finBloque', None],
    [F, 'LESS', None],
    [F, 'GREATER', None],
    [F, 'EQUALS', None],
    [F, 'DIFFERENT', None],
    [F, 'AND', None],
    [F, 'OR', None],
    [F, 'CONST_INT', ['CONST_INT']],
    [F, 'CONST_FLOAT', ['CONST_FLOAT']],
    [F, 'CONST_CHAR', None],
    [F, 'if', None],
    [F, 'else', None],
    [F, 'while', None],
    [F, 'do', None],
    [F, 'finInstruccion', None],
    [F, 'INCREMENT', None],
    [F, 'DECREMENT', None],
    [F, 'for', None],
    [F, 'int', None],
    [F, 'ASSIGNMENT', None],
    [F, 'float', None],
    [F, 'char', None],
    [F, 'void', None],
    [F, 'COMMA', None],
    [F, 'LBRACKET', None],
    [F, 'RBRACKET', None],
    [F, 'DOT', None],
    [F, 'PLUS', None],
    [F, 'MINUS', None],
    [F, 'TIMES', None],
    [F, 'DIVIDE', None],
    [F, 'MOD', None],
    [F, 'struct', None],
    [F, 'return', None],
    [F, 'eof', None],

    [F2, 'ID', [F]],
    [F2, 'main', None],
    [F2, 'LPAREN', None],
    [F2, 'RPAREN', None],
    [F2, 'inicioBloque', None],
    [F2, 'finBloque', None],
    [F2, 'LESS', None],
    [F2, 'GREATER', None],
    [F2, 'EQUALS', None],
    [F2, 'DIFFERENT', None],
    [F2, 'AND', None],
    [F2, 'OR', None],
    [F2, 'CONST_INT', [F]],
    [F2, 'CONST_FLOAT', [F]],
    [F2, 'CONST_CHAR', ['CONST_CHAR']],
    [F2, 'if', None],
    [F2, 'else', None],
    [F2, 'while', None],
    [F2, 'do', None],
    [F2, 'finInstruccion', None],
    [F2, 'INCREMENT', None],
    [F2, 'DECREMENT', None],
    [F2, 'for', None],
    [F2, 'int', None],
    [F2, 'ASSIGNMENT', None],
    [F2, 'float', None],
    [F2, 'char', None],
    [F2, 'void', None],
    [F2, 'COMMA', None],
    [F2, 'LBRACKET', None],
    [F2, 'RBRACKET', None],
    [F2, 'DOT', None],
    [F2, 'PLUS', None],
    [F2, 'MINUS', None],
    [F2, 'TIMES', None],
    [F2, 'DIVIDE', None],
    [F2, 'MOD', None],
    [F2, 'struct', None],
    [F2, 'return', None],
    [F2, 'eof', None],

    [F3, 'ID', [F2]],
    [F3, 'main', None],
    [F3, 'LPAREN', None],
    [F3, 'RPAREN', None],
    [F3, 'inicioBloque', None],
    [F3, 'finBloque', None],
    [F3, 'LESS', None],
    [F3, 'GREATER', None],
    [F3, 'EQUALS', None],
    [F3, 'DIFFERENT', None],
    [F3, 'AND', None],
    [F3, 'OR', None],
    [F3, 'CONST_INT', [F2]],
    [F3, 'CONST_FLOAT', [F2]],
    [F3, 'CONST_CHAR', [F2]],
    [F3, 'if', None],
    [F3, 'else', None],
    [F3, 'while', None],
    [F3, 'do', None],
    [F3, 'finInstruccion', ['vacia']],
    [F3, 'INCREMENT', None],
    [F3, 'DECREMENT', None],
    [F3, 'for', None],
    [F3, 'int', None],
    [F3, 'ASSIGNMENT', None],
    [F3, 'float', None],
    [F3, 'char', None],
    [F3, 'void', None],
    [F3, 'COMMA', None],
    [F3, 'LBRACKET', None],
    [F3, 'RBRACKET', None],
    [F3, 'DOT', None],
    [F3, 'PLUS', None],
    [F3, 'MINUS', None],
    [F3, 'TIMES', None],
    [F3, 'DIVIDE', None],
    [F3, 'MOD', None],
    [F3, 'struct', None],
    [F3, 'return', None],
    [F3, 'eof', None],

    [L, 'ID', None],
    [L, 'main', None],
    [L, 'LPAREN', None],
    [L, 'RPAREN', ['vacia']],
    [L, 'inicioBloque', None],
    [L, 'finBloque', None],
    [L, 'LESS', [O, F2, L]],
    [L, 'GREATER', [O, F2, L]],
    [L, 'EQUALS', [O, F2, L]],
    [L, 'DIFFERENT', [O, F2, L]],
    [L, 'AND', [O, F2, L]],
    [L, 'OR', [O, F2, L]],
    [L, 'CONST_INT', None],
    [L, 'CONST_FLOAT', None],
    [L, 'CONST_CHAR', None],
    [L, 'if', None],
    [L, 'else', None],
    [L, 'while', None],
    [L, 'do', None],
    [L, 'finInstruccion', None],
    [L, 'INCREMENT', None],
    [L, 'DECREMENT', None],
    [L, 'for', None],
    [L, 'int', None],
    [L, 'ASSIGNMENT', None],
    [L, 'float', None],
    [L, 'char', None],
    [L, 'void', None],
    [L, 'COMMA', None],
    [L, 'LBRACKET', None],
    [L, 'RBRACKET', None],
    [L, 'DOT', None],
    [L, 'PLUS', None],
    [L, 'MINUS', None],
    [L, 'TIMES', None],
    [L, 'DIVIDE', None],
    [L, 'MOD', None],
    [L, 'struct', None],
    [L, 'return', None],
    [L, 'eof', None],

    [C, 'ID', [F2, O, F2, L]],
    [C, 'main', None],
    [C, 'LPAREN', None],
    [C, 'RPAREN', None],
    [C, 'inicioBloque', None],
    [C, 'finBloque', None],
    [C, 'LESS', None],
    [C, 'GREATER', None],
    [C, 'EQUALS', None],
    [C, 'DIFFERENT', None],
    [C, 'AND', None],
    [C, 'OR', None],
    [C, 'CONST_INT', [F2, O, F2, L]],
    [C, 'CONST_FLOAT', [F2, O, F2, L]],
    [C, 'CONST_CHAR', [F2, O, F2, L]],
    [C, 'if', None],
    [C, 'else', None],
    [C, 'while', None],
    [C, 'do', None],
    [C, 'finInstruccion', None],
    [C, 'INCREMENT', None],
    [C, 'DECREMENT', None],
    [C, 'for', None],
    [C, 'int', None],
    [C, 'ASSIGNMENT', None],
    [C, 'float', None],
    [C, 'char', None],
    [C, 'void', None],
    [C, 'COMMA', None],
    [C, 'LBRACKET', None],
    [C, 'RBRACKET', None],
    [C, 'DOT', None],
    [C, 'PLUS', None],
    [C, 'MINUS', None],
    [C, 'TIMES', None],
    [C, 'DIVIDE', None],
    [C, 'MOD', None],
    [C, 'struct', None],
    [C, 'return', None],
    [C, 'eof', None],

    [I, 'ID', None],
    [I, 'main', None],
    [I, 'LPAREN', None],
    [I, 'RPAREN', None],
    [I, 'inicioBloque', None],
    [I, 'finBloque', None],
    [I, 'LESS', None],
    [I, 'GREATER', None],
    [I, 'EQUALS', None],
    [I, 'DIFFERENT', None],
    [I, 'AND', None],
    [I, 'OR', None],
    [I, 'CONST_INT', None],
    [I, 'CONST_FLOAT', None],
    [I, 'CONST_CHAR', None],
    [I, 'if', ['if', 'LPAREN', C, 'RPAREN', 'LBRACKET', S1, 'RBRACKET', E]],
    [I, 'else', None],
    [I, 'while', None],
    [I, 'do', None],
    [I, 'finInstruccion', None],
    [I, 'INCREMENT', None],
    [I, 'DECREMENT', None],
    [I, 'for', None],
    [I, 'int', None],
    [I, 'ASSIGNMENT', None],
    [I, 'float', None],
    [I, 'char', None],
    [I, 'void', None],
    [I, 'COMMA', None],
    [I, 'LBRACKET', None],
    [I, 'RBRACKET', None],
    [I, 'DOT', None],
    [I, 'PLUS', None],
    [I, 'MINUS', None],
    [I, 'TIMES', None],
    [I, 'DIVIDE', None],
    [I, 'MOD', None],
    [I, 'struct', None],
    [I, 'return', None],
    [I, 'eof', None],

    [E, 'ID', ['vacia']],
    [E, 'main', None],
    [E, 'LPAREN', None],
    [E, 'RPAREN', None],
    [E, 'inicioBloque', None],
    [E, 'finBloque', ['vacia']],
    [E, 'LESS', None],
    [E, 'GREATER', None],
    [E, 'EQUALS', None],
    [E, 'DIFFERENT', None],
    [E, 'AND', None],
    [E, 'OR', None],
    [E, 'CONST_INT', None],
    [E, 'CONST_FLOAT', None],
    [E, 'CONST_CHAR', None],
    [E, 'if', ['vacia']],
    [E, 'else', ['else', 'inicioBloque', S1, 'finBloque']],
    [E, 'while', ['vacia']],
    [E, 'do', ['vacia']],
    [E, 'finInstruccion', ['vacia']],
    [E, 'INCREMENT', None],
    [E, 'DECREMENT', None],
    [E, 'for', ['vacia']],
    [E, 'int', ['vacia']],
    [E, 'ASSIGNMENT', None],
    [E, 'float', ['vacia']],
    [E, 'char', ['vacia']],
    [E, 'void', None],
    [E, 'COMMA', None],
    [E, 'LBRACKET', None],
    [E, 'RBRACKET', None],
    [E, 'DOT', None],
    [E, 'PLUS', None],
    [E, 'MINUS', None],
    [E, 'TIMES', None],
    [E, 'DIVIDE', None],
    [E, 'MOD', None],
    [E, 'struct', ['vacia']],
    [E, 'return', ['vacia']],
    [E, 'eof', None],

    [W, 'ID', None],
    [W, 'main', None],
    [W, 'LPAREN', None],
    [W, 'RPAREN', None],
    [W, 'inicioBloque', None],
    [W, 'finBloque', None],
    [W, 'LESS', None],
    [W, 'GREATER', None],
    [W, 'EQUALS', None],
    [W, 'DIFFERENT', None],
    [W, 'AND', None],
    [W, 'OR', None],
    [W, 'CONST_INT', None],
    [W, 'CONST_FLOAT', None],
    [W, 'CONST_CHAR', None],
    [W, 'if', None],
    [W, 'else', None],
    [W, 'while', ['while', 'LPAREN', C, 'RPAREN', 'inicioBloque', S1, 'finBloque']],
    [W, 'do', None],
    [W, 'finInstruccion', None],
    [W, 'INCREMENT', None],
    [W, 'DECREMENT', None],
    [W, 'for', None],
    [W, 'int', None],
    [W, 'ASSIGNMENT', None],
    [W, 'float', None],
    [W, 'char', None],
    [W, 'void', None],
    [W, 'COMMA', None],
    [W, 'LBRACKET', None],
    [W, 'RBRACKET', None],
    [W, 'DOT', None],
    [W, 'PLUS', None],
    [W, 'MINUS', None],
    [W, 'TIMES', None],
    [W, 'DIVIDE', None],
    [W, 'MOD', None],
    [W, 'struct', None],
    [W, 'return', None],
    [W, 'eof', None],

    [G, 'ID', None],
    [G, 'main', None],
    [G, 'LPAREN', None],
    [G, 'RPAREN', None],
    [G, 'inicioBloque', None],
    [G, 'finBloque', None],
    [G, 'LESS', None],
    [G, 'GREATER', None],
    [G, 'EQUALS', None],
    [G, 'DIFFERENT', None],
    [G, 'AND', None],
    [G, 'OR', None],
    [G, 'CONST_INT', None],
    [G, 'CONST_FLOAT', None],
    [G, 'CONST_CHAR', None],
    [G, 'if', None],
    [G, 'else', None],
    [G, 'while', None],
    [G, 'do', ['do', 'inicioBloque', S1, 'finBloque', 'while', 'LPAREN', C, 'RPAREN', 'finInstruccion']],
    [G, 'finInstruccion', None],
    [G, 'INCREMENT', None],
    [G, 'DECREMENT', None],
    [G, 'for', None],
    [G, 'int', None],
    [G, 'ASSIGNMENT', None],
    [G, 'float', None],
    [G, 'char', None],
    [G, 'void', None],
    [G, 'COMMA', None],
    [G, 'LBRACKET', None],
    [G, 'RBRACKET', None],
    [G, 'DOT', None],
    [G, 'PLUS', None],
    [G, 'MINUS', None],
    [G, 'TIMES', None],
    [G, 'DIVIDE', None],
    [G, 'MOD', None],
    [G, 'struct', None],
    [G, 'return', None],
    [G, 'eof', None],

    [P, 'ID', None],
    [P, 'main', None],
    [P, 'LPAREN', None],
    [P, 'RPAREN', None],
    [P, 'inicioBloque', None],
    [P, 'finBloque', None],
    [P, 'LESS', None],
    [P, 'GREATER', None],
    [P, 'EQUALS', None],
    [P, 'DIFFERENT', None],
    [P, 'AND', None],
    [P, 'OR', None],
    [P, 'CONST_INT', None],
    [P, 'CONST_FLOAT', None],
    [P, 'CONST_CHAR', None],
    [P, 'if', None],
    [P, 'else', None],
    [P, 'while', None],
    [P, 'do', None],
    [P, 'finInstruccion', None],
    [P, 'INCREMENT', ['INCREMENT']],
    [P, 'DECREMENT', ['DECREMENT']],
    [P, 'for', None],
    [P, 'int', None],
    [P, 'ASSIGNMENT', None],
    [P, 'float', None],
    [P, 'char', None],
    [P, 'void', None],
    [P, 'COMMA', None],
    [P, 'LBRACKET', None],
    [P, 'RBRACKET', None],
    [P, 'DOT', None],
    [P, 'PLUS', None],
    [P, 'MINUS', None],
    [P, 'TIMES', None],
    [P, 'DIVIDE', None],
    [P, 'MOD', None],
    [P, 'struct', None],
    [P, 'return', None],
    [P, 'eof', None],

    [Q, 'ID', None],
    [Q, 'main', None],
    [Q, 'LPAREN', None],
    [Q, 'RPAREN', None],
    [Q, 'inicioBloque', None],
    [Q, 'finBloque', None],
    [Q, 'LESS', None],
    [Q, 'GREATER', None],
    [Q, 'EQUALS', None],
    [Q, 'DIFFERENT', None],
    [Q, 'AND', None],
    [Q, 'OR', None],
    [Q, 'CONST_INT', None],
    [Q, 'CONST_FLOAT', None],
    [Q, 'CONST_CHAR', None],
    [Q, 'if', None],
    [Q, 'else', None],
    [Q, 'while', None],
    [Q, 'do', None],
    [Q, 'finInstruccion', None],
    [Q, 'INCREMENT', None],
    [Q, 'DECREMENT', None],
    [Q, 'for',
     ['for', 'LPAREN', Q3, 'ID', Q4, 'finInstruccion', 'ID', O, F, 'finInstruccion', 'ID', P, 'RPAREN', 'inicioBloque',
      S1, 'finBloque']],
    [Q, 'int', None],
    [Q, 'ASSIGNMENT', None],
    [Q, 'float', None],
    [Q, 'char', None],
    [Q, 'void', None],
    [Q, 'COMMA', None],
    [Q, 'LBRACKET', None],
    [Q, 'RBRACKET', None],
    [Q, 'DOT', None],
    [Q, 'PLUS', None],
    [Q, 'MINUS', None],
    [Q, 'TIMES', None],
    [Q, 'DIVIDE', None],
    [Q, 'MOD', None],
    [Q, 'struct', None],
    [Q, 'return', None],
    [Q, 'eof', None],

    [Q3, 'ID', ['vacia']],
    [Q3, 'main', None],
    [Q3, 'LPAREN', None],
    [Q3, 'RPAREN', None],
    [Q3, 'inicioBloque', None],
    [Q3, 'finBloque', None],
    [Q3, 'LESS', None],
    [Q3, 'GREATER', None],
    [Q3, 'EQUALS', None],
    [Q3, 'DIFFERENT', None],
    [Q3, 'AND', None],
    [Q3, 'OR', None],
    [Q3, 'CONST_INT', None],
    [Q3, 'CONST_FLOAT', None],
    [Q3, 'CONST_CHAR', None],
    [Q3, 'if', None],
    [Q3, 'else', None],
    [Q3, 'while', None],
    [Q3, 'do', None],
    [Q3, 'finInstruccion', None],
    [Q3, 'INCREMENT', None],
    [Q3, 'DECREMENT', None],
    [Q3, 'for', None],
    [Q3, 'int', ['int']],
    [Q3, 'ASSIGNMENT', None],
    [Q3, 'float', None],
    [Q3, 'char', None],
    [Q3, 'void', None],
    [Q3, 'COMMA', None],
    [Q3, 'LBRACKET', None],
    [Q3, 'RBRACKET', None],
    [Q3, 'DOT', None],
    [Q3, 'PLUS', None],
    [Q3, 'MINUS', None],
    [Q3, 'TIMES', None],
    [Q3, 'DIVIDE', None],
    [Q3, 'MOD', None],
    [Q3, 'struct', None],
    [Q3, 'return', None],
    [Q3, 'eof', None],

    [Q4, 'ID', None],
    [Q4, 'main', None],
    [Q4, 'LPAREN', None],
    [Q4, 'RPAREN', None],
    [Q4, 'inicioBloque', None],
    [Q4, 'finBloque', None],
    [Q4, 'LESS', None],
    [Q4, 'GREATER', None],
    [Q4, 'EQUALS', None],
    [Q4, 'DIFFERENT', None],
    [Q4, 'AND', None],
    [Q4, 'OR', None],
    [Q4, 'CONST_INT', None],
    [Q4, 'CONST_FLOAT', None],
    [Q4, 'CONST_CHAR', None],
    [Q4, 'if', None],
    [Q4, 'else', None],
    [Q4, 'while', None],
    [Q4, 'do', None],
    [Q4, 'finInstruccion', ['vacia']],
    [Q4, 'INCREMENT', None],
    [Q4, 'DECREMENT', None],
    [Q4, 'for', None],
    [Q4, 'int', None],
    [Q4, 'ASSIGNMENT', ['ASSIGNMENT', 'CONST_INT']],
    [Q4, 'float', None],
    [Q4, 'char', None],
    [Q4, 'void', None],
    [Q4, 'COMMA', None],
    [Q4, 'LBRACKET', None],
    [Q4, 'RBRACKET', None],
    [Q4, 'DOT', None],
    [Q4, 'PLUS', None],
    [Q4, 'MINUS', None],
    [Q4, 'TIMES', None],
    [Q4, 'DIVIDE', None],
    [Q4, 'MOD', None],
    [Q4, 'struct', None],
    [Q4, 'return', None],
    [Q4, 'eof', None],

    [D, 'ID', None],
    [D, 'main', None],
    [D, 'LPAREN', None],
    [D, 'RPAREN', None],
    [D, 'inicioBloque', None],
    [D, 'finBloque', None],
    [D, 'LESS', None],
    [D, 'GREATER', None],
    [D, 'EQUALS', None],
    [D, 'DIFFERENT', None],
    [D, 'AND', None],
    [D, 'OR', None],
    [D, 'CONST_INT', None],
    [D, 'CONST_FLOAT', None],
    [D, 'CONST_CHAR', None],
    [D, 'if', None],
    [D, 'else', None],
    [D, 'while', None],
    [D, 'do', None],
    [D, 'finInstruccion', None],
    [D, 'INCREMENT', None],
    [D, 'DECREMENT', None],
    [D, 'for', None],
    [D, 'int', ['int']],
    [D, 'ASSIGNMENT', None],
    [D, 'float', ['float']],
    [D, 'char', ['char']],
    [D, 'void', None],
    [D, 'COMMA', None],
    [D, 'LBRACKET', None],
    [D, 'RBRACKET', None],
    [D, 'DOT', None],
    [D, 'PLUS', None],
    [D, 'MINUS', None],
    [D, 'TIMES', None],
    [D, 'DIVIDE', None],
    [D, 'MOD', None],
    [D, 'struct', None],
    [D, 'return', None],
    [D, 'eof', None],

    [D2, 'ID', None],
    [D2, 'main', None],
    [D2, 'LPAREN', None],
    [D2, 'RPAREN', None],
    [D2, 'inicioBloque', None],
    [D2, 'finBloque', None],
    [D2, 'LESS', None],
    [D2, 'GREATER', None],
    [D2, 'EQUALS', None],
    [D2, 'DIFFERENT', None],
    [D2, 'AND', None],
    [D2, 'OR', None],
    [D2, 'CONST_INT', None],
    [D2, 'CONST_FLOAT', None],
    [D2, 'CONST_CHAR', None],
    [D2, 'if', None],
    [D2, 'else', None],
    [D2, 'while', None],
    [D2, 'do', None],
    [D2, 'finInstruccion', None],
    [D2, 'INCREMENT', None],
    [D2, 'DECREMENT', None],
    [D2, 'for', None],
    [D2, 'int', [D]],
    [D2, 'ASSIGNMENT', None],
    [D2, 'float', [D]],
    [D2, 'char', [D]],
    [D2, 'void', ['void']],
    [D2, 'COMMA', None],
    [D2, 'LBRACKET', None],
    [D2, 'RBRACKET', None],
    [D2, 'DOT', None],
    [D2, 'PLUS', None],
    [D2, 'MINUS', None],
    [D2, 'TIMES', None],
    [D2, 'DIVIDE', None],
    [D2, 'MOD', None],
    [D2, 'struct', None],
    [D2, 'return', None],
    [D2, 'eof', None],

    [V, 'ID', None],
    [V, 'main', None],
    [V, 'LPAREN', None],
    [V, 'RPAREN', None],
    [V, 'inicioBloque', None],
    [V, 'finBloque', None],
    [V, 'LESS', None],
    [V, 'GREATER', None],
    [V, 'EQUALS', None],
    [V, 'DIFFERENT', None],
    [V, 'AND', None],
    [V, 'OR', None],
    [V, 'CONST_INT', None],
    [V, 'CONST_FLOAT', None],
    [V, 'CONST_CHAR', None],
    [V, 'if', None],
    [V, 'else', None],
    [V, 'while', None],
    [V, 'do', None],
    [V, 'finInstruccion', None],
    [V, 'INCREMENT', None],
    [V, 'DECREMENT', None],
    [V, 'for', None],
    [V, 'int', [D, 'ID', V1]],
    [V, 'ASSIGNMENT', None],
    [V, 'float', [D, 'ID', V1]],
    [V, 'char', [D, 'ID', V1]],
    [V, 'void', None],
    [V, 'COMMA', None],
    [V, 'LBRACKET', None],
    [V, 'RBRACKET', None],
    [V, 'DOT', None],
    [V, 'PLUS', None],
    [V, 'MINUS', None],
    [V, 'TIMES', None],
    [V, 'DIVIDE', None],
    [V, 'MOD', None],
    [V, 'struct', None],
    [V, 'return', None],
    [V, 'eof', None],

    [V1, 'ID', None],
    [V1, 'main', None],
    [V1, 'LPAREN', None],
    [V1, 'RPAREN', None],
    [V1, 'inicioBloque', None],
    [V1, 'finBloque', None],
    [V1, 'LESS', None],
    [V1, 'GREATER', None],
    [V1, 'EQUALS', None],
    [V1, 'DIFFERENT', None],
    [V1, 'AND', None],
    [V1, 'OR', None],
    [V1, 'CONST_INT', None],
    [V1, 'CONST_FLOAT', None],
    [V1, 'CONST_CHAR', None],
    [V1, 'if', None],
    [V1, 'else', None],
    [V1, 'while', None],
    [V1, 'do', None],
    [V1, 'finInstruccion', ['finInstruccion']],
    [V1, 'INCREMENT', None],
    [V1, 'DECREMENT', None],
    [V1, 'for', None],
    [V1, 'int', None],
    [V1, 'ASSIGNMENT', ['ASSIGNMENT', V2]],
    [V1, 'float', None],
    [V1, 'char', None],
    [V1, 'void', None],
    [V1, 'COMMA', ['COMMA', 'ID', V1]],
    [V1, 'LBRACKET', ['LBRACKET', 'CONST_INT', 'RBRACKET', V3]],
    [V1, 'RBRACKET', None],
    [V1, 'DOT', None],
    [V1, 'PLUS', None],
    [V1, 'MINUS', None],
    [V1, 'TIMES', None],
    [V1, 'DIVIDE', None],
    [V1, 'MOD', None],
    [V1, 'struct', None],
    [V1, 'return', None],
    [V1, 'eof', None],

    [V3, 'ID', None],
    [V3, 'main', None],
    [V3, 'LPAREN', None],
    [V3, 'RPAREN', None],
    [V3, 'inicioBloque', None],
    [V3, 'finBloque', None],
    [V3, 'LESS', None],
    [V3, 'GREATER', None],
    [V3, 'EQUALS', None],
    [V3, 'DIFFERENT', None],
    [V3, 'AND', None],
    [V3, 'OR', None],
    [V3, 'CONST_INT', None],
    [V3, 'CONST_FLOAT', None],
    [V3, 'CONST_CHAR', None],
    [V3, 'if', None],
    [V3, 'else', None],
    [V3, 'while', None],
    [V3, 'do', None],
    [V3, 'finInstruccion', None],
    [V3, 'INCREMENT', None],
    [V3, 'DECREMENT', None],
    [V3, 'for', None],
    [V3, 'int', None],
    [V3, 'ASSIGNMENT', ['ASSIGNMENT', 'inicioBloque', V5]],
    [V3, 'float', None],
    [V3, 'char', None],
    [V3, 'void', None],
    [V3, 'COMMA', ['COMMA', 'ID', V1]],
    [V3, 'LBRACKET', None],
    [V3, 'RBRACKET', None],
    [V3, 'DOT', None],
    [V3, 'PLUS', None],
    [V3, 'MINUS', None],
    [V3, 'TIMES', None],
    [V3, 'DIVIDE', None],
    [V3, 'MOD', None],
    [V3, 'struct', None],
    [V3, 'return', None],
    [V3, 'eof', None],

    [V5, 'ID', [F2, V6]],
    [V5, 'main', None],
    [V5, 'LPAREN', None],
    [V5, 'RPAREN', None],
    [V5, 'inicioBloque', None],
    [V5, 'finBloque', None],
    [V5, 'LESS', None],
    [V5, 'GREATER', None],
    [V5, 'EQUALS', None],
    [V5, 'DIFFERENT', None],
    [V5, 'AND', None],
    [V5, 'OR', None],
    [V5, 'CONST_INT', [F2, V6]],
    [V5, 'CONST_FLOAT', [F2, V6]],
    [V5, 'CONST_CHAR', [F2, V6]],
    [V5, 'if', None],
    [V5, 'else', None],
    [V5, 'while', None],
    [V5, 'do', None],
    [V5, 'finInstruccion', None],
    [V5, 'INCREMENT', None],
    [V5, 'DECREMENT', None],
    [V5, 'for', None],
    [V5, 'int', None],
    [V5, 'ASSIGNMENT', None],
    [V5, 'float', None],
    [V5, 'char', None],
    [V5, 'void', None],
    [V5, 'COMMA', None],
    [V5, 'LBRACKET', None],
    [V5, 'RBRACKET', None],
    [V5, 'DOT', None],
    [V5, 'PLUS', None],
    [V5, 'MINUS', None],
    [V5, 'TIMES', None],
    [V5, 'DIVIDE', None],
    [V5, 'MOD', None],
    [V5, 'struct', None],
    [V5, 'return', None],
    [V5, 'eof', None],

    [V6, 'ID', None],
    [V6, 'main', None],
    [V6, 'LPAREN', None],
    [V6, 'RPAREN', None],
    [V6, 'inicioBloque', None],
    [V6, 'finBloque', ['finBloque', V1]],
    [V6, 'LESS', None],
    [V6, 'GREATER', None],
    [V6, 'EQUALS', None],
    [V6, 'DIFFERENT', None],
    [V6, 'AND', None],
    [V6, 'OR', None],
    [V6, 'CONST_INT', None],
    [V6, 'CONST_FLOAT', None],
    [V6, 'CONST_CHAR', None],
    [V6, 'if', None],
    [V6, 'else', None],
    [V6, 'while', None],
    [V6, 'do', None],
    [V6, 'finInstruccion', None],
    [V6, 'INCREMENT', None],
    [V6, 'DECREMENT', None],
    [V6, 'for', None],
    [V6, 'int', None],
    [V6, 'ASSIGNMENT', None],
    [V6, 'float', None],
    [V6, 'char', None],
    [V6, 'void', None],
    [V6, 'COMMA', ['COMMA', F2, V6]],
    [V6, 'LBRACKET', None],
    [V6, 'RBRACKET', None],
    [V6, 'DOT', None],
    [V6, 'PLUS', None],
    [V6, 'MINUS', None],
    [V6, 'TIMES', None],
    [V6, 'DIVIDE', None],
    [V6, 'MOD', None],
    [V6, 'struct', None],
    [V6, 'return', None],
    [V6, 'eof', None],

    [V2, 'ID', [F2, V4]],
    [V2, 'main', None],
    [V2, 'LPAREN', None],
    [V2, 'RPAREN', None],
    [V2, 'inicioBloque', None],
    [V2, 'finBloque', None],
    [V2, 'LESS', None],
    [V2, 'GREATER', None],
    [V2, 'EQUALS', None],
    [V2, 'DIFFERENT', None],
    [V2, 'AND', None],
    [V2, 'OR', None],
    [V2, 'CONST_INT', [F2, V4]],
    [V2, 'CONST_FLOAT', [F2, V4]],
    [V2, 'CONST_CHAR', [F2, V4]],
    [V2, 'if', None],
    [V2, 'else', None],
    [V2, 'while', None],
    [V2, 'do', None],
    [V2, 'finInstruccion', None],
    [V2, 'INCREMENT', None],
    [V2, 'DECREMENT', None],
    [V2, 'for', None],
    [V2, 'int', None],
    [V2, 'ASSIGNMENT', None],
    [V2, 'float', None],
    [V2, 'char', None],
    [V2, 'void', None],
    [V2, 'COMMA', None],
    [V2, 'LBRACKET', None],
    [V2, 'RBRACKET', None],
    [V2, 'DOT', None],
    [V2, 'PLUS', None],
    [V2, 'MINUS', None],
    [V2, 'TIMES', None],
    [V2, 'DIVIDE', None],
    [V2, 'MOD', None],
    [V2, 'struct', None],
    [V2, 'return', None],
    [V2, 'eof', None],

    [V4, 'ID', None],
    [V4, 'main', None],
    [V4, 'LPAREN', None],
    [V4, 'RPAREN', None],
    [V4, 'inicioBloque', None],
    [V4, 'finBloque', None],
    [V4, 'LESS', None],
    [V4, 'GREATER', None],
    [V4, 'EQUALS', None],
    [V4, 'DIFFERENT', None],
    [V4, 'AND', None],
    [V4, 'OR', None],
    [V4, 'CONST_INT', None],
    [V4, 'CONST_FLOAT', None],
    [V4, 'CONST_CHAR', None],
    [V4, 'if', None],
    [V4, 'else', None],
    [V4, 'while', None],
    [V4, 'do', None],
    [V4, 'finInstruccion', ['finInstruccion']],
    [V4, 'INCREMENT', None],
    [V4, 'DECREMENT', None],
    [V4, 'for', None],
    [V4, 'int', None],
    [V4, 'ASSIGNMENT', None],
    [V4, 'float', None],
    [V4, 'char', None],
    [V4, 'void', None],
    [V4, 'COMMA', ['COMMA', 'ID', V1]],
    [V4, 'LBRACKET', None],
    [V4, 'RBRACKET', None],
    [V4, 'DOT', None],
    [V4, 'PLUS', None],
    [V4, 'MINUS', None],
    [V4, 'TIMES', None],
    [V4, 'DIVIDE', None],
    [V4, 'MOD', None],
    [V4, 'struct', None],
    [V4, 'return', None],
    [V4, 'eof', None],

    [B, 'ID', ['ID', B1]],
    [B, 'main', None],
    [B, 'LPAREN', None],
    [B, 'RPAREN', None],
    [B, 'inicioBloque', None],
    [B, 'finBloque', None],
    [B, 'LESS', None],
    [B, 'GREATER', None],
    [B, 'EQUALS', None],
    [B, 'DIFFERENT', None],
    [B, 'AND', None],
    [B, 'OR', None],
    [B, 'CONST_INT', None],
    [B, 'CONST_FLOAT', None],
    [B, 'CONST_CHAR', None],
    [B, 'if', None],
    [B, 'else', None],
    [B, 'while', None],
    [B, 'do', None],
    [B, 'finInstruccion', None],
    [B, 'INCREMENT', None],
    [B, 'DECREMENT', None],
    [B, 'for', None],
    [B, 'int', None],
    [B, 'ASSIGNMENT', None],
    [B, 'float', None],
    [B, 'char', None],
    [B, 'void', None],
    [B, 'COMMA', None],
    [B, 'LBRACKET', None],
    [B, 'RBRACKET', None],
    [B, 'DOT', None],
    [B, 'PLUS', None],
    [B, 'MINUS', None],
    [B, 'TIMES', None],
    [B, 'DIVIDE', None],
    [B, 'MOD', None],
    [B, 'struct', None],
    [B, 'return', None],
    [B, 'eof', None],

    [B1, 'ID', None],
    [B1, 'main', None],
    [B1, 'LPAREN', ['LPAREN', T2, 'RPAREN', S1, 'finInstruccion']],
    [B1, 'RPAREN', None],
    [B1, 'inicioBloque', None],
    [B1, 'finBloque', None],
    [B1, 'LESS', None],
    [B1, 'GREATER', None],
    [B1, 'EQUALS', None],
    [B1, 'DIFFERENT', None],
    [B1, 'AND', None],
    [B1, 'OR', None],
    [B1, 'CONST_INT', None],
    [B1, 'CONST_FLOAT', None],
    [B1, 'CONST_CHAR', None],
    [B1, 'if', None],
    [B1, 'else', None],
    [B1, 'while', None],
    [B1, 'do', None],
    [B1, 'finInstruccion', None],
    [B1, 'INCREMENT', None],
    [B1, 'DECREMENT', None],
    [B1, 'for', None],
    [B1, 'int', None],
    [B1, 'ASSIGNMENT', ['ASSIGNMENT', K, 'finInstruccion']],
    [B1, 'float', None],
    [B1, 'char', None],
    [B1, 'void', None],
    [B1, 'COMMA', None],
    [B1, 'LBRACKET', None],
    [B1, 'RBRACKET', None],
    [B1, 'DOT', ['DOT', 'ID', 'ASSIGNMENT', K]],
    [B1, 'PLUS', None],
    [B1, 'MINUS', None],
    [B1, 'TIMES', None],
    [B1, 'DIVIDE', None],
    [B1, 'MOD', None],
    [B1, 'struct', None],
    [B1, 'return', None],
    [B1, 'eof', None],

    [K, 'ID', [Q1, A]],
    [K, 'main', None],
    [K, 'LPAREN', [Q1, A]],
    [K, 'RPAREN', None],
    [K, 'inicioBloque', None],
    [K, 'finBloque', None],
    [K, 'LESS', None],
    [K, 'GREATER', None],
    [K, 'EQUALS', None],
    [K, 'DIFFERENT', None],
    [K, 'AND', None],
    [K, 'OR', None],
    [K, 'CONST_INT', [Q1, A]],
    [K, 'CONST_FLOAT', [Q1, A]],
    [K, 'CONST_CHAR', [Q1, A]],
    [K, 'if', None],
    [K, 'else', None],
    [K, 'while', None],
    [K, 'do', None],
    [K, 'finInstruccion', None],
    [K, 'INCREMENT', None],
    [K, 'DECREMENT', None],
    [K, 'for', None],
    [K, 'int', None],
    [K, 'ASSIGNMENT', None],
    [K, 'float', None],
    [K, 'char', None],
    [K, 'void', None],
    [K, 'COMMA', None],
    [K, 'LBRACKET', None],
    [K, 'RBRACKET', None],
    [K, 'DOT', None],
    [K, 'PLUS', None],
    [K, 'MINUS', None],
    [K, 'TIMES', None],
    [K, 'DIVIDE', None],
    [K, 'MOD', None],
    [K, 'struct', None],
    [K, 'return', None],
    [K, 'eof', None],

    [Q1, 'ID', [T1, Z]],
    [Q1, 'main', None],
    [Q1, 'LPAREN', [T1, Z]],
    [Q1, 'RPAREN', None],
    [Q1, 'inicioBloque', None],
    [Q1, 'finBloque', None],
    [Q1, 'LESS', None],
    [Q1, 'GREATER', None],
    [Q1, 'EQUALS', None],
    [Q1, 'DIFFERENT', None],
    [Q1, 'AND', None],
    [Q1, 'OR', None],
    [Q1, 'CONST_INT', [T1, Z]],
    [Q1, 'CONST_FLOAT', [T1, Z]],
    [Q1, 'CONST_CHAR', [T1, Z]],
    [Q1, 'if', None],
    [Q1, 'else', None],
    [Q1, 'while', None],
    [Q1, 'do', None],
    [Q1, 'finInstruccion', None],
    [Q1, 'INCREMENT', None],
    [Q1, 'DECREMENT', None],
    [Q1, 'for', None],
    [Q1, 'int', None],
    [Q1, 'ASSIGNMENT', None],
    [Q1, 'float', None],
    [Q1, 'char', None],
    [Q1, 'void', None],
    [Q1, 'COMMA', None],
    [Q1, 'LBRACKET', None],
    [Q1, 'RBRACKET', None],
    [Q1, 'DOT', None],
    [Q1, 'PLUS', None],
    [Q1, 'MINUS', None],
    [Q1, 'TIMES', None],
    [Q1, 'DIVIDE', None],
    [Q1, 'MOD', None],
    [Q1, 'struct', None],
    [Q1, 'return', None],
    [Q1, 'eof', None],

    [A, 'ID', ['vacia']],
    [A, 'main', None],
    [A, 'LPAREN', None],
    [A, 'RPAREN', ['vacia']],
    [A, 'inicioBloque', None],
    [A, 'finBloque', ['vacia']],
    [A, 'LESS', None],
    [A, 'GREATER', None],
    [A, 'EQUALS', None],
    [A, 'DIFFERENT', None],
    [A, 'AND', None],
    [A, 'OR', None],
    [A, 'CONST_INT', None],
    [A, 'CONST_FLOAT', None],
    [A, 'CONST_CHAR', None],
    [A, 'if', ['vacia']],
    [A, 'else', None],
    [A, 'while', ['vacia']],
    [A, 'do', ['vacia']],
    [A, 'finInstruccion', ['vacia']],
    [A, 'INCREMENT', None],
    [A, 'DECREMENT', None],
    [A, 'for', ['vacia']],
    [A, 'int', ['vacia']],
    [A, 'ASSIGNMENT', None],
    [A, 'float', ['vacia']],
    [A, 'char', ['vacia']],
    [A, 'void', None],
    [A, 'COMMA', None],
    [A, 'LBRACKET', None],
    [A, 'RBRACKET', None],
    [A, 'DOT', None],
    [A, 'PLUS', ['PLUS', Q1, A]],
    [A, 'MINUS', ['MINUS', Q1, A]],
    [A, 'TIMES', None],
    [A, 'DIVIDE', None],
    [A, 'MOD', None],
    [A, 'struct', ['vacia']],
    [A, 'return', ['vacia']],
    [A, 'eof', None],

    [T1, 'ID', [F2]],
    [T1, 'main', None],
    [T1, 'LPAREN', ['LPAREN', K, 'RPAREN']],
    [T1, 'RPAREN', None],
    [T1, 'inicioBloque', None],
    [T1, 'finBloque', None],
    [T1, 'LESS', None],
    [T1, 'GREATER', None],
    [T1, 'EQUALS', None],
    [T1, 'DIFFERENT', None],
    [T1, 'AND', None],
    [T1, 'OR', None],
    [T1, 'CONST_INT', [F2]],
    [T1, 'CONST_FLOAT', [F2]],
    [T1, 'CONST_CHAR', [F2]],
    [T1, 'if', None],
    [T1, 'else', None],
    [T1, 'while', None],
    [T1, 'do', None],
    [T1, 'finInstruccion', None],
    [T1, 'INCREMENT', None],
    [T1, 'DECREMENT', None],
    [T1, 'for', None],
    [T1, 'int', None],
    [T1, 'ASSIGNMENT', None],
    [T1, 'float', None],
    [T1, 'char', None],
    [T1, 'void', None],
    [T1, 'COMMA', None],
    [T1, 'LBRACKET', None],
    [T1, 'RBRACKET', None],
    [T1, 'DOT', None],
    [T1, 'PLUS', None],
    [T1, 'MINUS', None],
    [T1, 'TIMES', None],
    [T1, 'DIVIDE', None],
    [T1, 'MOD', None],
    [T1, 'struct', None],
    [T1, 'return', None],
    [T1, 'eof', None],

    [Z, 'ID', ['vacia']],
    [Z, 'main', None],
    [Z, 'LPAREN', None],
    [Z, 'RPAREN', ['vacia']],
    [Z, 'inicioBloque', None],
    [Z, 'finBloque', ['vacia']],
    [Z, 'LESS', None],
    [Z, 'GREATER', None],
    [Z, 'EQUALS', None],
    [Z, 'DIFFERENT', None],
    [Z, 'AND', None],
    [Z, 'OR', None],
    [Z, 'CONST_INT', None],
    [Z, 'CONST_FLOAT', None],
    [Z, 'CONST_CHAR', None],
    [Z, 'if', ['vacia']],
    [Z, 'else', None],
    [Z, 'while', ['vacia']],
    [Z, 'do', ['vacia']],
    [Z, 'finInstruccion', ['vacia']],
    [Z, 'INCREMENT', None],
    [Z, 'DECREMENT', None],
    [Z, 'for', ['vacia']],
    [Z, 'int', ['vacia']],
    [Z, 'ASSIGNMENT', None],
    [Z, 'float', ['vacia']],
    [Z, 'char', ['vacia']],
    [Z, 'void', None],
    [Z, 'COMMA', None],
    [Z, 'LBRACKET', None],
    [Z, 'RBRACKET', None],
    [Z, 'DOT', None],
    [Z, 'PLUS', ['vacia']],
    [Z, 'MINUS', ['vacia']],
    [Z, 'TIMES', ['TIMES', T1, Z]],
    [Z, 'DIVIDE', ['DIVIDE', T1, Z]],
    [Z, 'MOD', ['MOD', T1, Z]],
    [Z, 'struct', ['vacia']],
    [Z, 'return', ['vacia']],
    [Z, 'eof', None],

    [S1, 'ID', [B, S1]],
    [S1, 'main', None],
    [S1, 'LPAREN', None],
    [S1, 'RPAREN', None],
    [S1, 'inicioBloque', None],
    [S1, 'finBloque', ['vacia']],
    [S1, 'LESS', None],
    [S1, 'GREATER', None],
    [S1, 'EQUALS', None],
    [S1, 'DIFFERENT', None],
    [S1, 'AND', None],
    [S1, 'OR', None],
    [S1, 'CONST_INT', None],
    [S1, 'CONST_FLOAT', None],
    [S1, 'CONST_CHAR', None],
    [S1, 'if', [I, S1]],
    [S1, 'else', None],
    [S1, 'while', [W, S1]],
    [S1, 'do', [G, S1]],
    [S1, 'finInstruccion', ['vacia']],
    [S1, 'INCREMENT', None],
    [S1, 'DECREMENT', None],
    [S1, 'for', [Q, S1]],
    [S1, 'int', [V, S1]],
    [S1, 'ASSIGNMENT', None],
    [S1, 'float', [V, S1]],
    [S1, 'char', [V, S1]],
    [S1, 'void', None],
    [S1, 'COMMA', None],
    [S1, 'LBRACKET', None],
    [S1, 'RBRACKET', None],
    [S1, 'DOT', None],
    [S1, 'PLUS', None],
    [S1, 'MINUS', None],
    [S1, 'TIMES', None],
    [S1, 'DIVIDE', None],
    [S1, 'MOD', None],
    [S1, 'struct', ['struct', 'ID', 'ID', 'finInstruccion']],
    [S1, 'return', ['return', F3, 'finInstruccion']],
    [S1, 'eof', None],

    [T2, 'ID', ['ID', T3]],
    [T2, 'main', None],
    [T2, 'LPAREN', None],
    [T2, 'RPAREN', ['vacia']],
    [T2, 'inicioBloque', None],
    [T2, 'finBloque', None],
    [T2, 'LESS', None],
    [T2, 'GREATER', None],
    [T2, 'EQUALS', None],
    [T2, 'DIFFERENT', None],
    [T2, 'AND', None],
    [T2, 'OR', None],
    [T2, 'CONST_INT', ['CONST_INT', T3]],
    [T2, 'CONST_FLOAT', ['CONST_FLOAT', T3]],
    [T2, 'CONST_CHAR', None],
    [T2, 'if', None],
    [T2, 'else', None],
    [T2, 'while', None],
    [T2, 'do', None],
    [T2, 'finInstruccion', None],
    [T2, 'INCREMENT', None],
    [T2, 'DECREMENT', None],
    [T2, 'for', None],
    [T2, 'int', None],
    [T2, 'ASSIGNMENT', None],
    [T2, 'float', None],
    [T2, 'char', None],
    [T2, 'void', None],
    [T2, 'COMMA', None],
    [T2, 'LBRACKET', None],
    [T2, 'RBRACKET', None],
    [T2, 'DOT', None],
    [T2, 'PLUS', None],
    [T2, 'MINUS', None],
    [T2, 'TIMES', None],
    [T2, 'DIVIDE', None],
    [T2, 'MOD', None],
    [T2, 'struct', None],
    [T2, 'return', None],
    [T2, 'eof', None],

    [T3, 'ID', None],
    [T3, 'main', None],
    [T3, 'LPAREN', None],
    [T3, 'RPAREN', None],
    [T3, 'inicioBloque', None],
    [T3, 'finBloque', None],
    [T3, 'LESS', None],
    [T3, 'GREATER', None],
    [T3, 'EQUALS', None],
    [T3, 'DIFFERENT', None],
    [T3, 'AND', None],
    [T3, 'OR', None],
    [T3, 'CONST_INT', None],
    [T3, 'CONST_FLOAT', None],
    [T3, 'CONST_CHAR', None],
    [T3, 'if', None],
    [T3, 'else', None],
    [T3, 'while', None],
    [T3, 'do', None],
    [T3, 'finInstruccion', None],
    [T3, 'INCREMENT', None],
    [T3, 'DECREMENT', None],
    [T3, 'for', None],
    [T3, 'int', None],
    [T3, 'ASSIGNMENT', None],
    [T3, 'float', None],
    [T3, 'char', None],
    [T3, 'void', None],
    [T3, 'COMMA', ['COMMA', T2]],
    [T3, 'LBRACKET', None],
    [T3, 'RBRACKET', None],
    [T3, 'DOT', None],
    [T3, 'PLUS', None],
    [T3, 'MINUS', None],
    [T3, 'TIMES', None],
    [T3, 'DIVIDE', None],
    [T3, 'MOD', None],
    [T3, 'struct', None],
    [T3, 'return', None],
    [T3, 'eof', None],

    [T4, 'ID', None],
    [T4, 'main', None],
    [T4, 'LPAREN', None],
    [T4, 'RPAREN', [T5]],
    [T4, 'inicioBloque', None],
    [T4, 'finBloque', None],
    [T4, 'LESS', None],
    [T4, 'GREATER', None],
    [T4, 'EQUALS', None],
    [T4, 'DIFFERENT', None],
    [T4, 'AND', None],
    [T4, 'OR', None],
    [T4, 'CONST_INT', None],
    [T4, 'CONST_FLOAT', None],
    [T4, 'CONST_CHAR', None],
    [T4, 'if', None],
    [T4, 'else', None],
    [T4, 'while', None],
    [T4, 'do', None],
    [T4, 'finInstruccion', None],
    [T4, 'INCREMENT', None],
    [T4, 'DECREMENT', None],
    [T4, 'for', None],
    [T4, 'int', [D, 'ID', T5]],
    [T4, 'ASSIGNMENT', None],
    [T4, 'float', [D, 'ID', T5]],
    [T4, 'char', [D, 'ID', T5]],
    [T4, 'void', None],
    [T4, 'COMMA', [T5]],
    [T4, 'LBRACKET', None],
    [T4, 'RBRACKET', None],
    [T4, 'DOT', None],
    [T4, 'PLUS', None],
    [T4, 'MINUS', None],
    [T4, 'TIMES', None],
    [T4, 'DIVIDE', None],
    [T4, 'MOD', None],
    [T4, 'struct', None],
    [T4, 'return', None],
    [T4, 'eof', None],

    [T5, 'ID', None],
    [T5, 'main', None],
    [T5, 'LPAREN', None],
    [T5, 'RPAREN', ['vacia']],
    [T5, 'inicioBloque', None],
    [T5, 'finBloque', None],
    [T5, 'LESS', None],
    [T5, 'GREATER', None],
    [T5, 'EQUALS', None],
    [T5, 'DIFFERENT', None],
    [T5, 'AND', None],
    [T5, 'OR', None],
    [T5, 'CONST_INT', None],
    [T5, 'CONST_FLOAT', None],
    [T5, 'CONST_CHAR', None],
    [T5, 'if', None],
    [T5, 'else', None],
    [T5, 'while', None],
    [T5, 'do', None],
    [T5, 'finInstruccion', None],
    [T5, 'INCREMENT', None],
    [T5, 'DECREMENT', None],
    [T5, 'for', None],
    [T5, 'int', None],
    [T5, 'ASSIGNMENT', None],
    [T5, 'float', None],
    [T5, 'char', None],
    [T5, 'void', None],
    [T5, 'COMMA', ['COMMA', T4]],
    [T5, 'LBRACKET', None],
    [T5, 'RBRACKET', None],
    [T5, 'DOT', None],
    [T5, 'PLUS', None],
    [T5, 'MINUS', None],
    [T5, 'TIMES', None],
    [T5, 'DIVIDE', None],
    [T5, 'MOD', None],
    [T5, 'struct', None],
    [T5, 'return', None],
    [T5, 'eof', None],

    [ST, 'ID', None],
    [ST, 'main', None],
    [ST, 'LPAREN', None],
    [ST, 'RPAREN', None],
    [ST, 'inicioBloque', None],
    [ST, 'finBloque', None],
    [ST, 'LESS', None],
    [ST, 'GREATER', None],
    [ST, 'EQUALS', None],
    [ST, 'DIFFERENT', None],
    [ST, 'AND', None],
    [ST, 'OR', None],
    [ST, 'CONST_INT', None],
    [ST, 'CONST_FLOAT', None],
    [ST, 'CONST_CHAR', None],
    [ST, 'if', None],
    [ST, 'else', None],
    [ST, 'while', None],
    [ST, 'do', None],
    [ST, 'finInstruccion', None],
    [ST, 'INCREMENT', None],
    [ST, 'DECREMENT', None],
    [ST, 'for', None],
    [ST, 'int', None],
    [ST, 'ASSIGNMENT', None],
    [ST, 'float', None],
    [ST, 'char', None],
    [ST, 'void', None],
    [ST, 'COMMA', None],
    [ST, 'LBRACKET', None],
    [ST, 'RBRACKET', None],
    [ST, 'DOT', None],
    [ST, 'PLUS', None],
    [ST, 'MINUS', None],
    [ST, 'TIMES', None],
    [ST, 'DIVIDE', None],
    [ST, 'MOD', None],
    [ST, 'struct', ['struct', 'ID', 'inicioBloque', ST2, 'finBloque']],
    [ST, 'return', None],
    [ST, 'eof', None],

    [ST2, 'ID', None],
    [ST2, 'main', None],
    [ST2, 'LPAREN', None],
    [ST2, 'RPAREN', None],
    [ST2, 'inicioBloque', None],
    [ST2, 'finBloque', ['vacia']],
    [ST2, 'LESS', None],
    [ST2, 'GREATER', None],
    [ST2, 'EQUALS', None],
    [ST2, 'DIFFERENT', None],
    [ST2, 'AND', None],
    [ST2, 'OR', None],
    [ST2, 'CONST_INT', None],
    [ST2, 'CONST_FLOAT', None],
    [ST2, 'CONST_CHAR', None],
    [ST2, 'if', None],
    [ST2, 'else', None],
    [ST2, 'while', None],
    [ST2, 'do', None],
    [ST2, 'finInstruccion',   None],
    [ST2, 'INCREMENT', None],
    [ST2, 'DECREMENT', None],
    [ST2, 'for', None],
    [ST2, 'int', [V, ST2]],
    [ST2, 'ASSIGNMENT', None],
    [ST2, 'float', [V, ST2]],
    [ST2, 'char', [V, ST2]],
    [ST2, 'void', None],
    [ST2, 'COMMA', None],
    [ST2, 'LBRACKET',  None],
    [ST2, 'RBRACKET', None],
    [ST2, 'DOT', None],
    [ST2, 'PLUS', None],
    [ST2, 'MINUS', None],
    [ST2, 'TIMES', None],
    [ST2, 'DIVIDE', None],
    [ST2, 'MOD', None],
    [ST2, 'struct', None],
    [ST2, 'return', None],
    [ST2, 'eof', None],
]

stack = ['eof', 0]

# Build the lexer
lexer = lex.lex()


def miParser():
    f = open('fuente.c', 'r')
    lexer.input(f.read())

    tok = lexer.token()
    x = stack[-1]  # primer elemento de der a izq

    while True:
        print("VALOR DE X")
        print(x)
        print("VALOR DE STACK")
        print(stack)
        print("VALOR DE TOKEN")
        print(tok.value)
        print("\n\n--------------------------------------------------")

        if x == tok.type and x == 'eof':
            print("Cadena terminada exitosamente")
            return  # aceptar
        else:
            if x == tok.type and x != 'eof':
                print("entró aqui")
                stack.pop()
                x = stack[-1]
                tok = lexer.token()
                print(tok)

            if x in tokens and x != tok.type:
                print("entró aqui 2")
                print("Error: se esperaba ", x)
                print('en la posicion: ', tok.lexpos)

                # poner el token que se esperaba en la cadena
                # estrategia modificar cadana y reiniciar parser (no recomendado)
                print(stack)
                tok.type = x

            if x not in tokens:  # es no terminal
                print("entró aqui 3")
                celda = buscar_en_tabla(x, tok.type)
                print("===============================")
                print("X VALUE: ")
                print(x)
                print("TOK TYPE")
                print(tok.type)
                print("CELDA")
                print(celda)
                print("===============================")
                if celda is None:
                    print("\nERROR en línea: ", tok.lineno, ", NO SE ESPERABA token de tipo ", tok.type,
                          "  se esperaba  ", x, "  en  '", tok.value, "'\n")
                    return 0;
                else:
                    stack.pop()
                    agregar_pila(celda)
                    print(stack)
                    print("------------")
                    x = stack[-1]


def buscar_en_tabla(no_terminal, terminal):
    for i in range(len(tabla)):
        if tabla[i][0] == no_terminal and tabla[i][1] == terminal:
            return tabla[i][2]  # retorno la celda


def agregar_pila(produccion):
    for elemento in reversed(produccion):
        if elemento != 'vacia':  # la vacía no la inserta
            stack.append(elemento)


def main():
    miParser()
    # f = open('fuente.c', 'r')
    # lexer.input(f.read())
    # while True:
    #     tok = lexer.token()
    #     if not tok:
    #         break
    #     # print(tok)
    #     print(tok.type, "elemento:    '", tok.value, "'      ", tok.lineno, tok.lexpos)


if __name__ == "__main__":
    main()
