import ply.lex as lex

S = 0
D = 1
S1 = 2
I = 3
V = 4
W = 5
Q = 6
Q1 = 7
C = 8
P = 9
G = 10
E = 11
F = 12
L = 13
O = 14
V1 = 15
V2 = 16
V3 = 17
V4 = 18
V5 = 19
H = 20
N = 21
N1 = 22
R = 23
R1 = 24
B = 25
K = 26
A = 27
T1 = 28
Z = 29
T2 = 30
T3 = 31
T4 = 32
T5 = 33

# List of token names. Required
tokens = [
    "int_main",
    "declaration",
    "LPAREN",
    "RPAREN",
    "inicioBloque",
    "finBloque",
    "CONST_INT",
    "CONST_FLOAT",
    "EMPTY",  # empty char
    "INCREMENT",  # ++
    "DECREMENT",  # --
    "PLUS",
    "MINUS",
    "TIMES",
    "DIVIDE",
    "MOD",
    "AND",
    "OR",
    "DIFFERENT",
    "EQUALS",
    "LESS",
    "GREATER",
    "ID",
    "COMMA",
    "APOSTROPHE",  # '
    "finInstruccion",  # ;
    "COMMENT",
    "COMMENTBLOCK",
    "ASSIGNMENT",  # =
    "DOT",  # .
    "eof"  # $
]

reserved_words = {
    "int": "int",
    "void": "void",
    "return": "return",
    "float": "float",
    "char": "char",
    "struct": "struct",
    "if": "if",
    "else": "else",
    "do": "do",
    "while": "while",
    'break': 'break',  # se debe poner gramatica
    "for": "for"
}

# Add words reserved to tokens array
tokens += list(reserved_words.values())

# Regular expression rules for simple tokens
t_PLUS = r'\+'
t_MINUS = r'-'
t_TIMES = r'\*'
t_DIVIDE = r'/'
t_MOD = r"\%"
t_AND = r"\&\&"
t_OR = r"\|\|"
t_INCREMENT = r"\+\+"
t_DECREMENT = r"\-\-"
t_DIFFERENT = r"\!\="
t_EQUALS = r"\=\="
t_LESS = r"\<"
t_GREATER = r"\>"
t_LPAREN = r"\("
t_RPAREN = r"\)"
t_inicioBloque = r'\{'
t_finBloque = r'\}'
t_finInstruccion = r'\;'
t_ASSIGNMENT = r"\="
t_APOSTROPHE = r"\'"
t_EMPTY = r"\'\'"
t_COMMA = r'\,'
t_DOT = r'\.'
t_eof = r'\$'


# A regular expression rule

def t_int_main(t):
    r"int\s*\t*main"
    t.type = reserved_words.get(t.value, "int_main")  # Check for reserved words
    return t

def t_declaration(t):
    r'([a-zA-Z_{1}][a-zA-Z0-9_]+)(?=\()'
    t.type = reserved_words.get(t.value, "declaration")  # Check for reserved words
    return t

def t_COMMENT(t):
    r"\/\/.*"
    pass


def t_COMMENTBLOCK(t):
    r"\/\*(.|\n)*\*\/"
    pass

def t_ID(t):
    r'([a-z]|[A-Z]|_)([a-z]|[A-Z]|\d|_)*'
    t.type = reserved_words.get(t.value, "ID")  # Check for reserved words
    return t

def t_CONST_FLOAT(t):
    r'[-+]?[0-9]+(\.([0-9]+)?([eE][-+]?[0-9]+)?|[eE][-+]?[0-9]+)'
    t.value = float(t.value)
    return t

def t_CONST_INT(t):
    r"\d+(\.\d+)?"
    t.value = int(t.value)
    return t

# Define a rule so we can track line numbers
def t_newline(t):
    r'\n+'
    t.lexer.lineno += len(t.value)


# A string containing ignored characters (spaces and tabs)
t_ignore = " \t"


# Error handling rule
def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    t.lexer.skip(1)
    return t


tabla = [
    [D, 'int_main', None],
    [D, 'LPAREN', None],
    [D, 'RPAREN', None],
    [D, 'inicioBloque', None],
    [D, 'finBloque', None],
    [D, 'LESS', None],
    [D, 'GREATER', None],
    [D, 'EQUALS', None],
    [D, 'DIFFERENT', None],
    [D, 'AND', None],
    [D, 'OR', None],
    [D, 'ID', None],
    [D, 'CONST_INT',  None],
    [D, 'CONST_FLOAT',  None],
    [D, 'CONST_CHAR', None],
    [D, 'if', None],
    [D, 'else', None],
    [D, 'while', None],
    [D, 'do', None],
    [D, 'finInstruccion', None],
    [D, 'INCREMENT', None],
    [D, 'DECREMENT', None],
    [D, 'for', None],
    [D, 'int', ['int']],
    [D, 'ASSIGNMENT', None],
    [D, 'float', ['float']],
    [D, 'char', ['char']],
    [D, 'void', None],
    [D, 'declaration', None],
    [D, 'return', None],
    [D, 'COMMA', None],
    [D, 'PLUS', None],
    [D, 'MINUS', None],
    [D, 'TIMES', None],
    [D, 'DIVIDE', None],
    [D, 'MOD', None],
    [D, 'struct', None],
    [D, 'type', None],
    [D, 'member', None],
    [D, 'DOT', None],
    [D, 'eof', None],

    [D2, 'int_main', None],
    [D2, 'LPAREN', None],
    [D2, 'RPAREN', None],
    [D2, 'inicioBloque', None],
    [D2, 'finBloque', None],
    [D2, 'LESS', None],
    [D2, 'GREATER', None],
    [D2, 'EQUALS', None],
    [D2, 'DIFFERENT', None],
    [D2, 'AND', None],
    [D2, 'OR', None],
    [D2, 'ID', None],
    [D2, 'CONST_INT',  None],
    [D2, 'CONST_FLOAT',  None],
    [D2, 'CONST_CHAR', None],
    [D2, 'if', None],
    [D2, 'else', None],
    [D2, 'while', None],
    [D2, 'do', None],
    [D2, 'finInstruccion', None],
    [D2, 'INCREMENT', None],
    [D2, 'DECREMENT', None],
    [D2, 'for', None],
    [D2, 'int', [D]],
    [D2, 'ASSIGNMENT', None],
    [D2, 'float', [D]],
    [D2, 'char', [D]],
    [D2, 'void', ['void']],
    [D2, 'declaration', None],
    [D2, 'return', None],
    [D2, 'COMMA', None],
    [D2, 'PLUS', None],
    [D2, 'MINUS', None],
    [D2, 'TIMES', None],
    [D2, 'DIVIDE', None],
    [D2, 'MOD', None],
    [D2, 'struct', None],
    [D2, 'type', None],
    [D2, 'member', None],
    [D2, 'DOT', None],
    [D2, 'eof', None],

    [R, 'int_main', None],
    [R, 'LPAREN', None],
    [R, 'RPAREN', None],
    [R, 'inicioBloque', None],
    [R, 'finBloque', None],
    [R, 'LESS', None],
    [R, 'GREATER', None],
    [R, 'EQUALS', None],
    [R, 'DIFFERENT', None],
    [R, 'AND', None],
    [R, 'OR', None],
    [R, 'ID', None],
    [R, 'CONST_INT',  None],
    [R, 'CONST_FLOAT',  None],
    [R, 'CONST_CHAR', None],
    [R, 'if', None],
    [R, 'else', None],
    [R, 'while', None],
    [R, 'do', None],
    [R, 'finInstruccion', None],
    [R, 'INCREMENT', None],
    [R, 'DECREMENT', None],
    [R, 'for', None],
    [R, 'int', [D2, 'declaration', 'LPAREN', T4, 'RPAREN', 'inicioBloque', S1, R1, 'finBloque']],
    [R, 'ASSIGNMENT', None],
    [R, 'float', [D2, 'declaration', 'LPAREN', T4, 'RPAREN', 'inicioBloque', S1, R1, 'finBloque']],
    [R, 'char', [D2, 'declaration', 'LPAREN', T4, 'RPAREN', 'inicioBloque', S1, R1, 'finBloque']],
    [R, 'void', [D2, 'declaration', 'LPAREN', T4, 'RPAREN', 'inicioBloque', S1, R1, 'finBloque']],
    [R, 'declaration', None],
    [R, 'return', None],
    [R, 'COMMA', None],
    [R, 'PLUS', None],
    [R, 'MINUS', None],
    [R, 'TIMES', None],
    [R, 'DIVIDE', None],
    [R, 'MOD', None],
    [R, 'struct', None],
    [R, 'type', None],
    [R, 'member', None],
    [R, 'DOT', None],
    [R, 'eof', None],

    [R1, 'int_main', None],
    [R1, 'LPAREN', None],
    [R1, 'RPAREN', None],
    [R1, 'inicioBloque', None],
    [R1, 'finBloque', ['vacia']],
    [R1, 'LESS', None],
    [R1, 'GREATER', None],
    [R1, 'EQUALS', None],
    [R1, 'DIFFERENT', None],
    [R1, 'AND', None],
    [R1, 'OR', None],
    [R1, 'ID', None],
    [R1, 'CONST_INT',  None],
    [R1, 'CONST_FLOAT',  None],
    [R1, 'CONST_CHAR', None],
    [R1, 'if', None],
    [R1, 'else', None],
    [R1, 'while', None],
    [R1, 'do', None],
    [R1, 'finInstruccion', None],
    [R1, 'INCREMENT', None],
    [R1, 'DECREMENT', None],
    [R1, 'for', None],
    [R1, 'int', None],
    [R1, 'ASSIGNMENT', None],
    [R1, 'float', None],
    [R1, 'char', None],
    [R1, 'void', None],
    [R1, 'declaration', None],
    [R1, 'return', ['return', F3, 'finInstruccion']],
    [R1, 'COMMA', None],
    [R1, 'PLUS', None],
    [R1, 'MINUS', None],
    [R1, 'TIMES', None],
    [R1, 'DIVIDE', None],
    [R1, 'MOD', None],
    [R1, 'struct', None],
    [R1, 'type', None],
    [R1, 'member', None],
    [R1, 'DOT', None],
    [R1, 'eof', None],

    [V, 'int_main', None],
    [V, 'LPAREN', None],
    [V, 'RPAREN', None],
    [V, 'inicioBloque', None],
    [V, 'finBloque', None],
    [V, 'LESS', None],
    [V, 'GREATER', None],
    [V, 'EQUALS', None],
    [V, 'DIFFERENT', None],
    [V, 'AND', None],
    [V, 'OR', None],
    [V, 'ID', None],
    [V, 'CONST_INT', None],
    [V, 'CONST_FLOAT', None],
    [V, 'CONST_CHAR', None],
    [V, 'if', None],
    [V, 'else', None],
    [V, 'while', None],
    [V, 'do', None],
    [V, 'finInstruccion', None],
    [V, 'INCREMENT', None],
    [V, 'DECREMENT', None],
    [V, 'for', None],
    [V, 'int', [D, 'ID', V1]],
    [V, 'ASSIGNMENT', None],
    [V, 'float', [D, 'ID', V1]],
    [V, 'char', [D, 'ID', V1]],
    [V, 'void', None],
    [V, 'declaration', None],
    [V, 'return', None],
    [V, 'COMMA', None],
    [V, 'PLUS', None],
    [V, 'MINUS', None],
    [V, 'TIMES', None],
    [V, 'DIVIDE', None],
    [V, 'MOD', None],
    [V, 'struct', None],
    [V, 'type', None],
    [V, 'member', None],
    [V, 'DOT', None],
    [V, 'eof', None],

    [V1, 'int_main', None],
    [V1, 'LPAREN', None],
    [V1, 'RPAREN', None],
    [V1, 'inicioBloque', None],
    [V1, 'finBloque', None],
    [V1, 'LESS', None],
    [V1, 'GREATER', None],
    [V1, 'EQUALS', None],
    [V1, 'DIFFERENT', None],
    [V1, 'AND', None],
    [V1, 'OR', None],
    [V1, 'ID', None],
    [V1, 'CONST_INT', None],
    [V1, 'CONST_FLOAT', None],
    [V1, 'CONST_CHAR', None],
    [V1, 'if', None],
    [V1, 'else', None],
    [V1, 'while', None],
    [V1, 'do', None],
    [V1, 'finInstruccion', ['finInstruccion']],
    [V1, 'INCREMENT', None],
    [V1, 'DECREMENT', None],
    [V1, 'for', None],
    [V1, 'int', ['ASSIGNMENT', V2]],
    [V1, 'ASSIGNMENT', None],
    [V1, 'float', None],
    [V1, 'char', None],
    [V1, 'void', None],
    [V1, 'declaration', None],
    [V1, 'return', None],
    [V1, 'COMMA', ['COMMA', 'ID', V1]],
    [V1, 'PLUS', None],
    [V1, 'MINUS', None],
    [V1, 'TIMES', None],
    [V1, 'DIVIDE', None],
    [V1, 'MOD', None],
    [V1, 'struct', None],
    [V1, 'type', None],
    [V1, 'member', None],
    [V1, 'DOT', None],
    [V1, 'eof', None],

    [V2, 'int_main', None],
    [V2, 'LPAREN', None],
    [V2, 'RPAREN', None],
    [V2, 'inicioBloque', None],
    [V2, 'finBloque', None],
    [V2, 'LESS', None],
    [V2, 'GREATER', None],
    [V2, 'EQUALS', None],
    [V2, 'DIFFERENT', None],
    [V2, 'AND', None],
    [V2, 'OR', None],
    [V2, 'ID', [F2, V4]],
    [V2, 'CONST_INT', [F2, V4]],
    [V2, 'CONST_FLOAT', [F2, V4]],
    [V2, 'CONST_CHAR', [F2, V4]],
    [V2, 'if', None],
    [V2, 'else', None],
    [V2, 'while', None],
    [V2, 'do', None],
    [V2, 'finInstruccion', None],
    [V2, 'INCREMENT', None],
    [V2, 'DECREMENT', None],
    [V2, 'for', None],
    [V2, 'int', None],
    [V2, 'ASSIGNMENT', None],
    [V2, 'float', None],
    [V2, 'char', None],
    [V2, 'void', None],
    [V2, 'declaration', None],
    [V2, 'return', None],
    [V2, 'COMMA', None],
    [V2, 'PLUS', None],
    [V2, 'MINUS', None],
    [V2, 'TIMES', None],
    [V2, 'DIVIDE', None],
    [V2, 'MOD', None],
    [V2, 'struct', None],
    [V2, 'type', None],
    [V2, 'member', None],
    [V2, 'DOT', None],
    [V2, 'eof', None],

    [V4, 'int_main', None],
    [V4, 'LPAREN', None],
    [V4, 'RPAREN', None],
    [V4, 'inicioBloque', None],
    [V4, 'finBloque', None],
    [V4, 'LESS', None],
    [V4, 'GREATER', None],
    [V4, 'EQUALS', None],
    [V4, 'DIFFERENT', None],
    [V4, 'AND', None],
    [V4, 'OR', None],
    [V4, 'ID', None],
    [V4, 'CONST_INT', None],
    [V4, 'CONST_FLOAT', None],
    [V4, 'CONST_CHAR', None],
    [V4, 'if', None],
    [V4, 'else', None],
    [V4, 'while', None],
    [V4, 'do', None],
    [V4, 'finInstruccion', ['finInstruccion']],
    [V4, 'INCREMENT', None],
    [V4, 'DECREMENT', None],
    [V4, 'for', None],
    [V4, 'int', None],
    [V4, 'ASSIGNMENT', None],
    [V4, 'float', None],
    [V4, 'char', None],
    [V4, 'void', None],
    [V4, 'declaration', None],
    [V4, 'return', None],
    [V4, 'COMMA', ['COMMA', 'ID', V1]],
    [V4, 'PLUS', None],
    [V4, 'MINUS', None],
    [V4, 'TIMES', None],
    [V4, 'DIVIDE', None],
    [V4, 'MOD', None],
    [V4, 'struct', None],
    [V4, 'type', None],
    [V4, 'member', None],
    [V4, 'DOT', None],
    [V4, 'eof', None],

    [B, 'int_main', None],
    [B, 'LPAREN', None],
    [B, 'RPAREN', None],
    [B, 'inicioBloque', None],
    [B, 'finBloque', None],
    [B, 'LESS', None],
    [B, 'GREATER', None],
    [B, 'EQUALS', None],
    [B, 'DIFFERENT', None],
    [B, 'AND', None],
    [B, 'OR', None],
    [B, 'ID', ['ID','ASSIGNMENT',K,'finInstruccion']],
    [B, 'CONST_INT', None],
    [B, 'CONST_FLOAT', None],
    [B, 'CONST_CHAR', None],
    [B, 'if', None],
    [B, 'else', None],
    [B, 'while', None],
    [B, 'do', None],
    [B, 'finInstruccion', None],
    [B, 'INCREMENT', None],
    [B, 'DECREMENT', None],
    [B, 'for', None],
    [B, 'int', None],
    [B, 'ASSIGNMENT', None],
    [B, 'float', None],
    [B, 'char', None],
    [B, 'void', None],
    [B, 'declaration', None],
    [B, 'return', None],
    [B, 'COMMA', None],
    [B, 'PLUS', None],
    [B, 'MINUS', None],
    [B, 'TIMES', None],
    [B, 'DIVIDE', None],
    [B, 'MOD', None],
    [B, 'struct', None],
    [B, 'type', None],
    [B, 'member', None],
    [B, 'DOT', None],
    [B, 'eof', None],

    [K, 'int_main', None],
    [K, 'LPAREN', [Q1,A]],
    [K, 'RPAREN', None],
    [K, 'inicioBloque', None],
    [K, 'finBloque', None],
    [K, 'LESS', None],
    [K, 'GREATER', None],
    [K, 'EQUALS', None],
    [K, 'DIFFERENT', None],
    [K, 'AND', None],
    [K, 'OR', None],
    [K, 'ID', [Q1,A]],
    [K, 'CONST_INT', [Q1,A]],
    [K, 'CONST_FLOAT', [Q1,A]],
    [K, 'CONST_CHAR', None],
    [K, 'if', None],
    [K, 'else', None],
    [K, 'while', None],
    [K, 'do', None],
    [K, 'finInstruccion', None],
    [K, 'INCREMENT', None],
    [K, 'DECREMENT', None],
    [K, 'for', None],
    [K, 'int', None],
    [K, 'ASSIGNMENT', None],
    [K, 'float', None],
    [K, 'char', None],
    [K, 'void', None],
    [K, 'declaration', None],
    [K, 'return', None],
    [K, 'COMMA', None],
    [K, 'PLUS', None],
    [K, 'MINUS', None],
    [K, 'TIMES', None],
    [K, 'DIVIDE', None],
    [K, 'MOD', None],
    [K, 'struct', None],
    [K, 'type', None],
    [K, 'member', None],
    [K, 'DOT', None],
    [K, 'eof', None],

    [Q1, 'int_main', None],
    [Q1, 'LPAREN', [T1,Z]],
    [Q1, 'RPAREN', None],
    [Q1, 'inicioBloque', None],
    [Q1, 'finBloque', None],
    [Q1, 'LESS', None],
    [Q1, 'GREATER', None],
    [Q1, 'EQUALS', None],
    [Q1, 'DIFFERENT', None],
    [Q1, 'AND', None],
    [Q1, 'OR', None],
    [Q1, 'ID', [T1,Z]],
    [Q1, 'CONST_INT', [T1,Z]],
    [Q1, 'CONST_FLOAT', [T1,Z]],
    [Q1, 'CONST_CHAR', None],
    [Q1, 'if', None],
    [Q1, 'else', None],
    [Q1, 'while', None],
    [Q1, 'do', None],
    [Q1, 'finInstruccion', None],
    [Q1, 'INCREMENT', None],
    [Q1, 'DECREMENT', None],
    [Q1, 'for', None],
    [Q1, 'int', None],
    [Q1, 'ASSIGNMENT', None],
    [Q1, 'float', None],
    [Q1, 'char', None],
    [Q1, 'void', None],
    [Q1, 'declaration', None],
    [Q1, 'return', None],
    [Q1, 'COMMA', None],
    [Q1, 'PLUS', None],
    [Q1, 'MINUS', None],
    [Q1, 'TIMES', None],
    [Q1, 'DIVIDE', None],
    [Q1, 'MOD', None],
    [Q1, 'struct', None],
    [Q1, 'type', None],
    [Q1, 'member', None],
    [Q1, 'DOT', None],
    [Q1, 'eof', None],

    [A, 'int_main', None],
    [A, 'LPAREN', None],
    [A, 'RPAREN', ['vacia']],
    [A, 'inicioBloque', None],
    [A, 'finBloque', None],
    [A, 'LESS', None],
    [A, 'GREATER', None],
    [A, 'EQUALS', None],
    [A, 'DIFFERENT', None],
    [A, 'AND', None],
    [A, 'OR', None],
    [A, 'ID', None],
    [A, 'CONST_INT', None],
    [A, 'CONST_FLOAT', None],
    [A, 'CONST_CHAR', None],
    [A, 'if', None],
    [A, 'else', None],
    [A, 'while', None],
    [A, 'do', None],
    [A, 'finInstruccion', ['vacia']],
    [A, 'INCREMENT', None],
    [A, 'DECREMENT', None],
    [A, 'for', None],
    [A, 'int', None],
    [A, 'ASSIGNMENT', None],
    [A, 'float', None],
    [A, 'char', None],
    [A, 'void', None],
    [A, 'declaration', None],
    [A, 'return', None],
    [A, 'COMMA', None],
    [A, 'PLUS', ['PLUS', Q1, A]],
    [A, 'MINUS', ['MINUS', Q1, A]],
    [A, 'TIMES', None],
    [A, 'DIVIDE', None],
    [A, 'MOD', None],
    [A, 'struct', None],
    [A, 'type', None],
    [A, 'member', None],
    [A, 'DOT', None],
    [A, 'eof', None],

    [T1, 'int_main', None],
    [T1, 'LPAREN', ['LPAREN', K, 'RPAREN']],
    [T1, 'RPAREN', None],
    [T1, 'inicioBloque', None],
    [T1, 'finBloque', None],
    [T1, 'LESS', None],
    [T1, 'GREATER', None],
    [T1, 'EQUALS', None],
    [T1, 'DIFFERENT', None],
    [T1, 'AND', None],
    [T1, 'OR', None],
    [T1, 'ID', [F]],
    [T1, 'CONST_INT',  [F]],
    [T1, 'CONST_FLOAT',  [F]],
    [T1, 'CONST_CHAR', None],
    [T1, 'if', None],
    [T1, 'else', None],
    [T1, 'while', None],
    [T1, 'do', None],
    [T1, 'finInstruccion', None],
    [T1, 'INCREMENT', None],
    [T1, 'DECREMENT', None],
    [T1, 'for', None],
    [T1, 'int', None],
    [T1, 'ASSIGNMENT', None],
    [T1, 'float', None],
    [T1, 'char', None],
    [T1, 'void', None],
    [T1, 'declaration', None],
    [T1, 'return', None],
    [T1, 'COMMA', None],
    [T1, 'PLUS', None],
    [T1, 'MINUS', None],
    [T1, 'TIMES', None],
    [T1, 'DIVIDE', None],
    [T1, 'MOD', None],
    [T1, 'struct', None],
    [T1, 'type', None],
    [T1, 'member', None],
    [T1, 'DOT', None],
    [T1, 'eof', None],

    [Z, 'int_main', None],
    [Z, 'LPAREN', None],
    [Z, 'RPAREN', ['vacia']],
    [Z, 'inicioBloque', None],
    [Z, 'finBloque', None],
    [Z, 'LESS', None],
    [Z, 'GREATER', None],
    [Z, 'EQUALS', None],
    [Z, 'DIFFERENT', None],
    [Z, 'AND', None],
    [Z, 'OR', None],
    [Z, 'ID', None],
    [Z, 'CONST_INT',  None],
    [Z, 'CONST_FLOAT',  None],
    [Z, 'CONST_CHAR', None],
    [Z, 'if', None],
    [Z, 'else', None],
    [Z, 'while', None],
    [Z, 'do', None],
    [Z, 'finInstruccion', ['vacia']],
    [Z, 'INCREMENT', None],
    [Z, 'DECREMENT', None],
    [Z, 'for', None],
    [Z, 'int', None],
    [Z, 'ASSIGNMENT', None],
    [Z, 'float', None],
    [Z, 'char', None],
    [Z, 'void', None],
    [Z, 'declaration', None],
    [Z, 'return', None],
    [Z, 'COMMA', None],
    [Z, 'PLUS', ['vacia']],
    [Z, 'MINUS', ['vacia']],
    [Z, 'TIMES', ['TIMES', T1, Z]],
    [Z, 'DIVIDE', ['DIVIDE', T1, Z]],
    [Z, 'MOD', ['MOD', T1, Z]],
    [Z, 'struct', None],
    [Z, 'type', None],
    [Z, 'member', None],
    [Z, 'DOT', None],
    [Z, 'eof', None],

    [H, 'int_main', None],
    [H, 'LPAREN', None],
    [H, 'RPAREN', None],
    [H, 'inicioBloque', None],
    [H, 'finBloque', None],
    [H, 'LESS', None],
    [H, 'GREATER', None],
    [H, 'EQUALS', None],
    [H, 'DIFFERENT', None],
    [H, 'AND', None],
    [H, 'OR', None],
    [H, 'ID', None],
    [H, 'CONST_INT',  None],
    [H, 'CONST_FLOAT',  None],
    [H, 'CONST_CHAR', None],
    [H, 'if', None],
    [H, 'else', None],
    [H, 'while', None],
    [H, 'do', None],
    [H, 'finInstruccion', None],
    [H, 'INCREMENT', None],
    [H, 'DECREMENT', None],
    [H, 'for', None],
    [H, 'int', None],
    [H, 'ASSIGNMENT', None],
    [H, 'float', None],
    [H, 'char', None],
    [H, 'void', None],
    [H, 'declaration', None],
    [H, 'return', None],
    [H, 'COMMA', None],
    [H, 'PLUS', None],
    [H, 'MINUS', None],
    [H, 'TIMES', None],
    [H, 'DIVIDE', None],
    [H, 'MOD', None],
    [H, 'struct', ['struct','type','inicioBloque', M, 'finBloque', N]],
    [H, 'type', None],
    [H, 'member', None],
    [H, 'DOT', None],
    [H, 'eof', None],

    [N, 'int_main', None],
    [N, 'LPAREN', None],
    [N, 'RPAREN', None],
    [N, 'inicioBloque', None],
    [N, 'finBloque', None],
    [N, 'LESS', None],
    [N, 'GREATER', None],
    [N, 'EQUALS', None],
    [N, 'DIFFERENT', None],
    [N, 'AND', None],
    [N, 'OR', None],
    [N, 'ID', ['ID', N1]],
    [N, 'CONST_INT',  None],
    [N, 'CONST_FLOAT',  None],
    [N, 'CONST_CHAR', None],
    [N, 'if', None],
    [N, 'else', None],
    [N, 'while', None],
    [N, 'do', None],
    [N, 'finInstruccion', None],
    [N, 'INCREMENT', None],
    [N, 'DECREMENT', None],
    [N, 'for', None],
    [N, 'int', None],
    [N, 'ASSIGNMENT', None],
    [N, 'float', None],
    [N, 'char', None],
    [N, 'void', None],
    [N, 'declaration', None],
    [N, 'return', None],
    [N, 'COMMA', None],
    [N, 'PLUS', None],
    [N, 'MINUS', None],
    [N, 'TIMES', None],
    [N, 'DIVIDE', None],
    [N, 'MOD', None],
    [N, 'struct', None],
    [N, 'type', None],
    [N, 'member', None],
    [N, 'DOT', None],
    [N, 'eof', None],

    [N1, 'int_main', None],
    [N1, 'LPAREN', None],
    [N1, 'RPAREN', None],
    [N1, 'inicioBloque', None],
    [N1, 'finBloque', None],
    [N1, 'LESS', None],
    [N1, 'GREATER', None],
    [N1, 'EQUALS', None],
    [N1, 'DIFFERENT', None],
    [N1, 'AND', None],
    [N1, 'OR', None],
    [N1, 'ID', None],
    [N1, 'CONST_INT',  None],
    [N1, 'CONST_FLOAT',  None],
    [N1, 'CONST_CHAR', None],
    [N1, 'if', None],
    [N1, 'else', None],
    [N1, 'while', None],
    [N1, 'do', None],
    [N1, 'finInstruccion', ['finInstruccion']],
    [N1, 'INCREMENT', None],
    [N1, 'DECREMENT', None],
    [N1, 'for', None],
    [N1, 'int', None],
    [N1, 'ASSIGNMENT', None],
    [N1, 'float', None],
    [N1, 'char', None],
    [N1, 'void', None],
    [N1, 'declaration', None],
    [N1, 'return', None],
    [N1, 'COMMA', ['COMMA', N]],
    [N1, 'PLUS', None],
    [N1, 'MINUS', None],
    [N1, 'TIMES', None],
    [N1, 'DIVIDE', None],
    [N1, 'MOD', None],
    [N1, 'struct', None],
    [N1, 'type', None],
    [N1, 'member', None],
    [N1, 'DOT', None],
    [N1, 'eof', None],

    [S2, 'int_main', ['vacia']],
    [S2, 'LPAREN', None],
    [S2, 'RPAREN', None],
    [S2, 'inicioBloque', None],
    [S2, 'finBloque', None],
    [S2, 'LESS', None],
    [S2, 'GREATER', None],
    [S2, 'EQUALS', None],
    [S2, 'DIFFERENT', None],
    [S2, 'AND', None],
    [S2, 'OR', None],
    [S2, 'ID', None],
    [S2, 'CONST_INT',  None],
    [S2, 'CONST_FLOAT',  None],
    [S2, 'CONST_CHAR', None],
    [S2, 'if', None],
    [S2, 'else', None],
    [S2, 'while', None],
    [S2, 'do', None],
    [S2, 'finInstruccion', None],
    [S2, 'INCREMENT', None],
    [S2, 'DECREMENT', None],
    [S2, 'for', None],
    [S2, 'int', [R, S2]],
    [S2, 'ASSIGNMENT', None],
    [S2, 'float', [R, S2]],
    [S2, 'char', [R, S2]],
    [S2, 'void', [R, S2]],
    [S2, 'declaration', None],
    [S2, 'return', None],
    [S2, 'COMMA', None],
    [S2, 'PLUS', None],
    [S2, 'MINUS', None],
    [S2, 'TIMES', None],
    [S2, 'DIVIDE', None],
    [S2, 'MOD', None],
    [S2, 'struct', [H, S2]],
    [S2, 'type', None],
    [S2, 'member', None],
    [S2, 'DOT', None],
    [S2, 'eof', None],

    [S1, 'int_main', None],
    [S1, 'LPAREN', None],
    [S1, 'RPAREN', None],
    [S1, 'inicioBloque', None],
    [S1, 'finBloque', None],
    [S1, 'LESS', None],
    [S1, 'GREATER', None],
    [S1, 'EQUALS', None],
    [S1, 'DIFFERENT', None],
    [S1, 'AND', None],
    [S1, 'OR', None],
    [S1, 'ID', [B, S1]],
    [S1, 'CONST_INT',  None],
    [S1, 'CONST_FLOAT',  None],
    [S1, 'CONST_CHAR', None],
    [S1, 'if', [I, S1]],
    [S1, 'else', None],
    [S1, 'while', [W, S1]],
    [S1, 'do', [G, S1]],
    [S1, 'finInstruccion', None],
    [S1, 'INCREMENT', None],
    [S1, 'DECREMENT', None],
    [S1, 'for', [Q, S1]],
    [S1, 'int', [V, S1]],
    [S1, 'ASSIGNMENT', None],
    [S1, 'float', [V, S1]],
    [S1, 'char', [V, S1]],
    [S1, 'void', None],
    [S1, 'declaration', ['declaration', 'LPAREN', T2, 'RPAREN', S1, 'finInstruccion']],
    [S1, 'return', ['return', 'CONST_INT', 'finInstruccion']],
    [S1, 'COMMA', None],
    [S1, 'PLUS', None],
    [S1, 'MINUS', None],
    [S1, 'TIMES', None],
    [S1, 'DIVIDE', None],
    [S1, 'MOD', None],
    [S1, 'struct', ['struct', 'type', 'ID', 'finInstruccion', S1]],
    [S1, 'type', None],
    [S1, 'member', ['member', 'DOT', B, 'finInstruccion', S1]],
    [S1, 'DOT', None],
    [S1, 'eof', None],

    [M, 'int_main', None],
    [M, 'LPAREN', None],
    [M, 'RPAREN', None],
    [M, 'inicioBloque', None],
    [M, 'finBloque', None],
    [M, 'LESS', None],
    [M, 'GREATER', None],
    [M, 'EQUALS', None],
    [M, 'DIFFERENT', None],
    [M, 'AND', None],
    [M, 'OR', None],
    [M, 'ID', None],
    [M, 'CONST_INT',  None],
    [M, 'CONST_FLOAT',  None],
    [M, 'CONST_CHAR', None],
    [M, 'if', None],
    [M, 'else', None],
    [M, 'while', None],
    [M, 'do', None],
    [M, 'finInstruccion', None],
    [M, 'INCREMENT', None],
    [M, 'DECREMENT', None],
    [M, 'for', None],
    [M, 'int', [D, 'member', V1]],
    [M, 'ASSIGNMENT', None],
    [M, 'float', [D, 'member', V1]],
    [M, 'char', [D, 'member', V1]],
    [M, 'void', None],
    [M, 'declaration', None],
    [M, 'return', None],
    [M, 'COMMA', None],
    [M, 'PLUS', None],
    [M, 'MINUS', None],
    [M, 'TIMES', None],
    [M, 'DIVIDE', None],
    [M, 'MOD', None],
    [M, 'struct', None],
    [M, 'type', None],
    [M, 'member', None],
    [M, 'DOT', None],
    [M, 'eof', None],

    [M1, 'int_main', None],
    [M1, 'LPAREN', None],
    [M1, 'RPAREN', None],
    [M1, 'inicioBloque', None],
    [M1, 'finBloque', None],
    [M1, 'LESS', None],
    [M1, 'GREATER', None],
    [M1, 'EQUALS', None],
    [M1, 'DIFFERENT', None],
    [M1, 'AND', None],
    [M1, 'OR', None],
    [M1, 'ID', None],
    [M1, 'CONST_INT',  None],
    [M1, 'CONST_FLOAT',  None],
    [M1, 'CONST_CHAR', None],
    [M1, 'if', None],
    [M1, 'else', None],
    [M1, 'while', None],
    [M1, 'do', None],
    [M1, 'finInstruccion', ['finInstruccion']],
    [M1, 'INCREMENT', None],
    [M1, 'DECREMENT', None],
    [M1, 'for', None],
    [M1, 'int', None],
    [M1, 'ASSIGNMENT', ['ASSIGNMENT', M2]],
    [M1, 'float', None],
    [M1, 'char', None],
    [M1, 'void', None],
    [M1, 'declaration', None],
    [M1, 'return', None],
    [M1, 'COMMA', ['COMMA', 'member', M1]],
    [M1, 'PLUS', None],
    [M1, 'MINUS', None],
    [M1, 'TIMES', None],
    [M1, 'DIVIDE', None],
    [M1, 'MOD', None],
    [M1, 'struct', None],
    [M1, 'type', None],
    [M1, 'member', None],
    [M1, 'DOT', None],
    [M1, 'eof', None],

    [M2, 'int_main', None],
    [M2, 'LPAREN', None],
    [M2, 'RPAREN', None],
    [M2, 'inicioBloque', None],
    [M2, 'finBloque', None],
    [M2, 'LESS', None],
    [M2, 'GREATER', None],
    [M2, 'EQUALS', None],
    [M2, 'DIFFERENT', None],
    [M2, 'AND', None],
    [M2, 'OR', None],
    [M2, 'ID', [F2, M4]],
    [M2, 'CONST_INT',  [F2, M4]],
    [M2, 'CONST_FLOAT',  [F2, M4]],
    [M2, 'CONST_CHAR', [F2, M4]],
    [M2, 'if', None],
    [M2, 'else', None],
    [M2, 'while', None],
    [M2, 'do', None],
    [M2, 'finInstruccion', None],
    [M2, 'INCREMENT', None],
    [M2, 'DECREMENT', None],
    [M2, 'for', None],
    [M2, 'int', None],
    [M2, 'ASSIGNMENT', None],
    [M2, 'float', None],
    [M2, 'char', None],
    [M2, 'void', None],
    [M2, 'declaration', None],
    [M2, 'return', None],
    [M2, 'COMMA', None],
    [M2, 'PLUS', None],
    [M2, 'MINUS', None],
    [M2, 'TIMES', None],
    [M2, 'DIVIDE', None],
    [M2, 'MOD', None],
    [M2, 'struct', None],
    [M2, 'type', None],
    [M2, 'member', None],
    [M2, 'DOT', None],
    [M2, 'eof', None],

    [M4, 'int_main', None],
    [M4, 'LPAREN', None],
    [M4, 'RPAREN', None],
    [M4, 'inicioBloque', None],
    [M4, 'finBloque', None],
    [M4, 'LESS', None],
    [M4, 'GREATER', None],
    [M4, 'EQUALS', None],
    [M4, 'DIFFERENT', None],
    [M4, 'AND', None],
    [M4, 'OR', None],
    [M4, 'ID', None],
    [M4, 'CONST_INT',  None],
    [M4, 'CONST_FLOAT',  None],
    [M4, 'CONST_CHAR', None],
    [M4, 'if', None],
    [M4, 'else', None],
    [M4, 'while', None],
    [M4, 'do', None],
    [M4, 'finInstruccion', ['finInstruccion']],
    [M4, 'INCREMENT', None],
    [M4, 'DECREMENT', None],
    [M4, 'for', None],
    [M4, 'int', None],
    [M4, 'ASSIGNMENT', None],
    [M4, 'float', None],
    [M4, 'char', None],
    [M4, 'void', None],
    [M4, 'declaration', None],
    [M4, 'return', None],
    [M4, 'COMMA', ['COMMA', 'member', M1]],
    [M4, 'PLUS', None],
    [M4, 'MINUS', None],
    [M4, 'TIMES', None],
    [M4, 'DIVIDE', None],
    [M4, 'MOD', None],
    [M4, 'struct', None],
    [M4, 'type', None],
    [M4, 'member', None],
    [M4, 'DOT', None],
    [M4, 'eof', None],

    [T2, 'int_main', None],
    [T2, 'LPAREN', None],
    [T2, 'RPAREN', ['vacia']],
    [T2, 'inicioBloque', None],
    [T2, 'finBloque', None],
    [T2, 'LESS', None],
    [T2, 'GREATER', None],
    [T2, 'EQUALS', None],
    [T2, 'DIFFERENT', None],
    [T2, 'AND', None],
    [T2, 'OR', None],
    [T2, 'ID', ['ID', T3]],
    [T2, 'CONST_INT',  ['CONST_INT', T3]],
    [T2, 'CONST_FLOAT',  ['CONST_FLOAT', T3]],
    [T2, 'CONST_CHAR', None],
    [T2, 'if', None],
    [T2, 'else', None],
    [T2, 'while', None],
    [T2, 'do', None],
    [T2, 'finInstruccion', None],
    [T2, 'INCREMENT', None],
    [T2, 'DECREMENT', None],
    [T2, 'for', None],
    [T2, 'int', None],
    [T2, 'ASSIGNMENT', None],
    [T2, 'float', None],
    [T2, 'char', None],
    [T2, 'void', None],
    [T2, 'declaration', None],
    [T2, 'return', None],
    [T2, 'COMMA', None],
    [T2, 'PLUS', None],
    [T2, 'MINUS', None],
    [T2, 'TIMES', None],
    [T2, 'DIVIDE', None],
    [T2, 'MOD', None],
    [T2, 'struct', None],
    [T2, 'type', None],
    [T2, 'member', None],
    [T2, 'DOT', None],
    [T2, 'eof', None],

    [T3, 'int_main', None],
    [T3, 'LPAREN', None],
    [T3, 'RPAREN', None],
    [T3, 'inicioBloque', None],
    [T3, 'finBloque', None],
    [T3, 'LESS', None],
    [T3, 'GREATER', None],
    [T3, 'EQUALS', None],
    [T3, 'DIFFERENT', None],
    [T3, 'AND', None],
    [T3, 'OR', None],
    [T3, 'ID', None],
    [T3, 'CONST_INT',  None],
    [T3, 'CONST_FLOAT',  None],
    [T3, 'CONST_CHAR', None],
    [T3, 'if', None],
    [T3, 'else', None],
    [T3, 'while', None],
    [T3, 'do', None],
    [T3, 'finInstruccion', None],
    [T3, 'INCREMENT', None],
    [T3, 'DECREMENT', None],
    [T3, 'for', None],
    [T3, 'int', None],
    [T3, 'ASSIGNMENT', None],
    [T3, 'float', None],
    [T3, 'char', None],
    [T3, 'void', None],
    [T3, 'declaration', None],
    [T3, 'return', None],
    [T3, 'COMMA', ['COMMA', T2]],
    [T3, 'PLUS', None],
    [T3, 'MINUS', None],
    [T3, 'TIMES', None],
    [T3, 'DIVIDE', None],
    [T3, 'MOD', None],
    [T3, 'struct', None],
    [T3, 'type', None],
    [T3, 'member', None],
    [T3, 'DOT', None],
    [T3, 'eof', None],

    [T4, 'int_main', None],
    [T4, 'LPAREN', None],
    [T4, 'RPAREN', None],
    [T4, 'inicioBloque', None],
    [T4, 'finBloque', None],
    [T4, 'LESS', None],
    [T4, 'GREATER', None],
    [T4, 'EQUALS', None],
    [T4, 'DIFFERENT', None],
    [T4, 'AND', None],
    [T4, 'OR', None],
    [T4, 'ID', None],
    [T4, 'CONST_INT',  None],
    [T4, 'CONST_FLOAT',  None],
    [T4, 'CONST_CHAR', None],
    [T4, 'if', None],
    [T4, 'else', None],
    [T4, 'while', None],
    [T4, 'do', None],
    [T4, 'finInstruccion', None],
    [T4, 'INCREMENT', None],
    [T4, 'DECREMENT', None],
    [T4, 'for', None],
    [T4, 'int', [D, 'ID', T5]],
    [T4, 'ASSIGNMENT', None],
    [T4, 'float', [D, 'ID', T5]],
    [T4, 'char', [D, 'ID', T5]],
    [T4, 'void', None],
    [T4, 'declaration', None],
    [T4, 'return', None],
    [T4, 'COMMA', None],
    [T4, 'PLUS', None],
    [T4, 'MINUS', None],
    [T4, 'TIMES', None],
    [T4, 'DIVIDE', None],
    [T4, 'MOD', None],
    [T4, 'struct', None],
    [T4, 'type', None],
    [T4, 'member', None],
    [T4, 'DOT', None],
    [T4, 'eof', None],

    [T5, 'int_main', None],
    [T5, 'LPAREN', None],
    [T5, 'RPAREN', ['vacia']],
    [T5, 'inicioBloque', None],
    [T5, 'finBloque', None],
    [T5, 'LESS', None],
    [T5, 'GREATER', None],
    [T5, 'EQUALS', None],
    [T5, 'DIFFERENT', None],
    [T5, 'AND', None],
    [T5, 'OR', None],
    [T5, 'ID', None],
    [T5, 'CONST_INT',  None],
    [T5, 'CONST_FLOAT',  None],
    [T5, 'CONST_CHAR', None],
    [T5, 'if', None],
    [T5, 'else', None],
    [T5, 'while', None],
    [T5, 'do', None],
    [T5, 'finInstruccion', None],
    [T5, 'INCREMENT', None],
    [T5, 'DECREMENT', None],
    [T5, 'for', None],
    [T5, 'int', None],
    [T5, 'ASSIGNMENT', None],
    [T5, 'float', None],
    [T5, 'char', None],
    [T5, 'void', None],
    [T5, 'declaration', None],
    [T5, 'return', None],
    [T5, 'COMMA', ['COMMA', T4]],
    [T5, 'PLUS', None],
    [T5, 'MINUS', None],
    [T5, 'TIMES', None],
    [T5, 'DIVIDE', None],
    [T5, 'MOD', None],
    [T5, 'struct', None],
    [T5, 'type', None],
    [T5, 'member', None],
    [T5, 'DOT', None],
    [T5, 'eof', None]
]

stack = ['eof', 0]

# Build the lexer
lexer = lex.lex()


def miParser():
    f = open('fuente.c', 'r')
    lexer.input(f.read())

    tok = lexer.token()
    x = stack[-1]  # primer elemento de der a izq

    while True:
        print(tok.type, "elemento:    '" ,tok.value, "'      " ,tok.lineno, tok.lexpos, "valor de x: ", x)

        if x == tok.type and x == 'eof':
            print("Cadena terminada exitosamente")
            return  # aceptar
        else:
            if x == tok.type and x != 'eof':
                print("entró aqui")
                stack.pop()
                x = stack[-1]
                tok = lexer.token()
                print(tok)
            if x in tokens and x != tok.type:
                print("Error: se esperaba ", x)
                print('en la posicion: ', tok.lexpos)

                # poner el token que se esperaba en la cadena
                # estrategia modificar cadana y reiniciar parser (no recomendado)
                print(stack)
                tok.type = x

            if x not in tokens:  # es no terminal
                celda = buscar_en_tabla(x, tok.type)
                if celda is None:
                    print("Error: NO se esperaba", tok.type, " se esperaba: ", x)
                    print("En posición:", tok.lexpos)
                    print(tok.type, "elemento:    '", tok.value, "'      ", tok.lineno, tok.lexpos, "valor de x: ", x)
                    return 0;
                else:
                    stack.pop()
                    agregar_pila(celda)
                    print(stack)
                    print("------------")
                    x = stack[-1]


def buscar_en_tabla(no_terminal, terminal):
    for i in range(len(tabla)):
        if tabla[i][0] == no_terminal and tabla[i][1] == terminal:
            return tabla[i][2]  # retorno la celda


def agregar_pila(produccion):
    for elemento in reversed(produccion):
        if elemento != 'vacia':  # la vacía no la inserta
            stack.append(elemento)


def main():
    # miParser()
    f = open('fuente.c', 'r')
    lexer.input(f.read())
    while True:
        tok = lexer.token()
        if not tok:
            break
        # print(tok)
        print(tok.type, "elemento:    '" ,tok.value, "'      " ,tok.lineno, tok.lexpos)


if __name__ == "__main__":
    main()
