symbols = {
    "LPAREN": "' ( '",
    "RPAREN": "' ) '",
    "inicioBloque": "' { '",
    "finBloque": "' } '",
    "LBRACKET": "' [ '",
    "RBRACKET": "' ] '",
    "CONST_INT": "CONST_INT",
    "CONST_FLOAT": "CONST_FLOAT",
    "CONST_CHAR": "CONST_CHAR",
    "INCREMENT": "' ++ '",
    "DECREMENT": "' -- '",
    "PLUS": "' + '",
    "MINUS": "' - '",
    "TIMES": "' * '",
    "DIVIDE": "' / '",
    "MOD": "' % '",
    "AND": "' && '",
    "OR": "' || '",
    "DIFFERENT": "' != '",
    "EQUALS": "' == '",
    "LESS": "' < '",
    "GREATER": "' > '",
    "ID": "ID",
    "COMMA": "' , '",
    "finInstruccion": "' ; '",
    "ASSIGNMENT": "' = '",
    "DOT": "' . '",
    "eof": "eof",
    "main": "main",
    "int": "int",
    "void": "void",
    "return": "return",
    "float": "float",
    "char": "char",
    "struct": "struct",
    "if": "if",
    "else": "else",
    "do": "do",
    "while": "while",
    "for": "for",
    'break': 'break'
}

getSymbol = {
    "LPAREN": "(",
    "RPAREN": ")",
    "inicioBloque": "{",
    "finBloque": "}",
    "LBRACKET": "[",
    "RBRACKET": "]",
    "CONST_INT": "1",
    "CONST_FLOAT": "1.0",
    "CONST_CHAR": "'a'",
    "INCREMENT": "++",
    "DECREMENT": "--",
    "PLUS": "+",
    "MINUS": "-",
    "TIMES": "*",
    "DIVIDE": "/",
    "MOD": "%",
    "AND": "&&",
    "OR": "||",
    "DIFFERENT": "!=",
    "EQUALS": "==",
    "LESS": "<",
    "GREATER": ">",
    "ID": "ID",
    "COMMA": ",",
    "finInstruccion": ";",
    "ASSIGNMENT": "=",
    "DOT": ".",
    "eof": "$",
    "main": "main",
    "int": "int",
    "void": "void",
    "return": "return",
    "float": "float",
    "char": "char",
    "struct": "struct",
    "if": "if",
    "else": "else",
    "do": "do",
    "while": "while",
    "for": "for",
    'break': 'break',
    "vacia": ""
}

